//! Bulk operations for PosCashMovement entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreatePosCashMovementDto;
use crate::application::service::PosCashMovementService;
use crate::domain::entity::PosCashMovement;

/// Bulk operation handler for PosCashMovement entities.
///
/// Wraps `PosCashMovementService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type PosCashMovementBulkService = GenericBulkService<PosCashMovement, CreatePosCashMovementDto, PosCashMovementService>;

// <<< CUSTOM
// END CUSTOM
