//! PosOpeningEntry DTOs (Data Transfer Objects)
//!
//! Auto-generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::PosOpeningEntry;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::PosSessionStatus;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new PosOpeningEntry
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreatePosOpeningEntryDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "pos_profile_id")]
    pub pos_profile_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "branch_id")]
    pub branch_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "cashier_party_id")]
    pub cashier_party_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "opened_at")]
    pub opened_at: DateTime<Utc>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "opening_balances")]
    pub opening_balances: Option<serde_json::Value>,
    pub status: PosSessionStatus,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a PosOpeningEntry
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdatePosOpeningEntryDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "pos_profile_id")]
    pub pos_profile_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "branch_id")]
    pub branch_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "cashier_party_id")]
    pub cashier_party_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "opened_at")]
    pub opened_at: DateTime<Utc>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "opening_balances")]
    pub opening_balances: Option<serde_json::Value>,
    pub status: PosSessionStatus,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a PosOpeningEntry
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchPosOpeningEntryDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "pos_profile_id")]
    pub pos_profile_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "branch_id")]
    pub branch_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "cashier_party_id")]
    pub cashier_party_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "opened_at")]
    pub opened_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "opening_balances")]
    pub opening_balances: Option<serde_json::Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<PosSessionStatus>,
}

impl PatchPosOpeningEntryDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.pos_profile_id.is_some() || self.branch_id.is_some() || self.cashier_party_id.is_some() || self.opened_at.is_some() || self.opening_balances.is_some() || self.status.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for PosOpeningEntry entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PosOpeningEntryResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub pos_profile_id: Uuid,
    pub branch_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub cashier_party_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    pub opened_at: DateTime<Utc>,
    pub opening_balances: Option<serde_json::Value>,
    pub status: PosSessionStatus,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for PosOpeningEntry entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PosOpeningEntryListResponseDto {
    /// List of items
    pub items: Vec<PosOpeningEntryResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl PosOpeningEntryListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<PosOpeningEntryResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PosOpeningEntrySummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub pos_profile_id: Uuid,
    pub branch_id: Option<Uuid>,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<PosOpeningEntry> for PosOpeningEntryResponseDto {
    fn from(entity: PosOpeningEntry) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            pos_profile_id: entity.pos_profile_id,
            branch_id: entity.branch_id,
            cashier_party_id: entity.cashier_party_id,
            opened_at: entity.opened_at,
            opening_balances: entity.opening_balances,
            status: entity.status,
            metadata: entity.metadata,
        }
    }
}

impl From<PosOpeningEntry> for PosOpeningEntrySummaryDto {
    fn from(entity: PosOpeningEntry) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            pos_profile_id: entity.pos_profile_id,
            branch_id: entity.branch_id,
            created_at,
        }
    }
}

impl From<CreatePosOpeningEntryDto> for PosOpeningEntry {
    fn from(dto: CreatePosOpeningEntryDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            pos_profile_id: dto.pos_profile_id,
            branch_id: dto.branch_id,
            cashier_party_id: dto.cashier_party_id,
            opened_at: dto.opened_at,
            opening_balances: dto.opening_balances,
            status: dto.status,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&PosOpeningEntry> for PosOpeningEntryResponseDto {
    fn from(entity: &PosOpeningEntry) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            pos_profile_id: entity.pos_profile_id.clone(),
            branch_id: entity.branch_id.clone(),
            cashier_party_id: entity.cashier_party_id.clone(),
            opened_at: entity.opened_at.clone(),
            opening_balances: entity.opening_balances.clone(),
            status: entity.status.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreatePosOpeningEntryDto> for PosOpeningEntry {
    fn from_create_dto(dto: CreatePosOpeningEntryDto) -> backbone_core::ServiceResult<Self> {
        Ok(PosOpeningEntry::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdatePosOpeningEntryDto> for PosOpeningEntry {
    fn apply_update(mut self, dto: UpdatePosOpeningEntryDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.pos_profile_id = dto.pos_profile_id;
        self.branch_id = dto.branch_id;
        self.cashier_party_id = dto.cashier_party_id;
        self.opened_at = dto.opened_at;
        self.opening_balances = dto.opening_balances;
        self.status = dto.status;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to PosOpeningEntry here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
