//! PosProfile DTOs (Data Transfer Objects)
//!
//! Auto-generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::PosProfile;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new PosProfile
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreatePosProfileDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "branch_id")]
    pub branch_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 140)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "default_customer_id")]
    pub default_customer_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 3)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub currency: String,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "income_account_id")]
    pub income_account_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "receivable_account_id")]
    pub receivable_account_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "cash_account_id")]
    pub cash_account_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "write_off_account_id")]
    pub write_off_account_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "tax_account_id")]
    pub tax_account_id: Option<Uuid>,
    #[serde(alias = "tax_rate")]
    pub tax_rate: Decimal,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "warehouse_id")]
    pub warehouse_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "cogs_account_id")]
    pub cogs_account_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "inventory_account_id")]
    pub inventory_account_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "allow_discount")]
    pub allow_discount: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_active")]
    pub is_active: bool,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a PosProfile
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdatePosProfileDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "branch_id")]
    pub branch_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 140)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "default_customer_id")]
    pub default_customer_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 3)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub currency: String,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "income_account_id")]
    pub income_account_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "receivable_account_id")]
    pub receivable_account_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "cash_account_id")]
    pub cash_account_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "write_off_account_id")]
    pub write_off_account_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "tax_account_id")]
    pub tax_account_id: Option<Uuid>,
    #[serde(alias = "tax_rate")]
    pub tax_rate: Decimal,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "warehouse_id")]
    pub warehouse_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "cogs_account_id")]
    pub cogs_account_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "inventory_account_id")]
    pub inventory_account_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "allow_discount")]
    pub allow_discount: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_active")]
    pub is_active: bool,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a PosProfile
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchPosProfileDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "branch_id")]
    pub branch_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 140)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "default_customer_id")]
    pub default_customer_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 3)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub currency: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "income_account_id")]
    pub income_account_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "receivable_account_id")]
    pub receivable_account_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "cash_account_id")]
    pub cash_account_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "write_off_account_id")]
    pub write_off_account_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "tax_account_id")]
    pub tax_account_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "tax_rate")]
    pub tax_rate: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "warehouse_id")]
    pub warehouse_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "cogs_account_id")]
    pub cogs_account_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "inventory_account_id")]
    pub inventory_account_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "allow_discount")]
    pub allow_discount: Option<bool>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "is_active")]
    pub is_active: Option<bool>,
}

impl PatchPosProfileDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.branch_id.is_some() || self.name.is_some() || self.default_customer_id.is_some() || self.currency.is_some() || self.income_account_id.is_some() || self.receivable_account_id.is_some() || self.cash_account_id.is_some() || self.write_off_account_id.is_some() || self.tax_account_id.is_some() || self.tax_rate.is_some() || self.warehouse_id.is_some() || self.cogs_account_id.is_some() || self.inventory_account_id.is_some() || self.allow_discount.is_some() || self.is_active.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for PosProfile entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PosProfileResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    pub branch_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    pub default_customer_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub currency: String,
    pub income_account_id: Option<Uuid>,
    pub receivable_account_id: Option<Uuid>,
    pub cash_account_id: Option<Uuid>,
    pub write_off_account_id: Option<Uuid>,
    pub tax_account_id: Option<Uuid>,
    pub tax_rate: Decimal,
    pub warehouse_id: Option<Uuid>,
    pub cogs_account_id: Option<Uuid>,
    pub inventory_account_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub allow_discount: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_active: bool,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for PosProfile entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PosProfileListResponseDto {
    /// List of items
    pub items: Vec<PosProfileResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl PosProfileListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<PosProfileResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PosProfileSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub branch_id: Option<Uuid>,
    pub name: String,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<PosProfile> for PosProfileResponseDto {
    fn from(entity: PosProfile) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            branch_id: entity.branch_id,
            name: entity.name,
            default_customer_id: entity.default_customer_id,
            currency: entity.currency,
            income_account_id: entity.income_account_id,
            receivable_account_id: entity.receivable_account_id,
            cash_account_id: entity.cash_account_id,
            write_off_account_id: entity.write_off_account_id,
            tax_account_id: entity.tax_account_id,
            tax_rate: entity.tax_rate,
            warehouse_id: entity.warehouse_id,
            cogs_account_id: entity.cogs_account_id,
            inventory_account_id: entity.inventory_account_id,
            allow_discount: entity.allow_discount,
            is_active: entity.is_active,
            metadata: entity.metadata,
        }
    }
}

impl From<PosProfile> for PosProfileSummaryDto {
    fn from(entity: PosProfile) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            branch_id: entity.branch_id,
            name: entity.name,
            created_at,
        }
    }
}

impl From<CreatePosProfileDto> for PosProfile {
    fn from(dto: CreatePosProfileDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            branch_id: dto.branch_id,
            name: dto.name,
            default_customer_id: dto.default_customer_id,
            currency: dto.currency,
            income_account_id: dto.income_account_id,
            receivable_account_id: dto.receivable_account_id,
            cash_account_id: dto.cash_account_id,
            write_off_account_id: dto.write_off_account_id,
            tax_account_id: dto.tax_account_id,
            tax_rate: dto.tax_rate,
            warehouse_id: dto.warehouse_id,
            cogs_account_id: dto.cogs_account_id,
            inventory_account_id: dto.inventory_account_id,
            allow_discount: dto.allow_discount,
            is_active: dto.is_active,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&PosProfile> for PosProfileResponseDto {
    fn from(entity: &PosProfile) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            branch_id: entity.branch_id.clone(),
            name: entity.name.clone(),
            default_customer_id: entity.default_customer_id.clone(),
            currency: entity.currency.clone(),
            income_account_id: entity.income_account_id.clone(),
            receivable_account_id: entity.receivable_account_id.clone(),
            cash_account_id: entity.cash_account_id.clone(),
            write_off_account_id: entity.write_off_account_id.clone(),
            tax_account_id: entity.tax_account_id.clone(),
            tax_rate: entity.tax_rate.clone(),
            warehouse_id: entity.warehouse_id.clone(),
            cogs_account_id: entity.cogs_account_id.clone(),
            inventory_account_id: entity.inventory_account_id.clone(),
            allow_discount: entity.allow_discount.clone(),
            is_active: entity.is_active.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreatePosProfileDto> for PosProfile {
    fn from_create_dto(dto: CreatePosProfileDto) -> backbone_core::ServiceResult<Self> {
        Ok(PosProfile::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdatePosProfileDto> for PosProfile {
    fn apply_update(mut self, dto: UpdatePosProfileDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.branch_id = dto.branch_id;
        self.name = dto.name;
        self.default_customer_id = dto.default_customer_id;
        self.currency = dto.currency;
        self.income_account_id = dto.income_account_id;
        self.receivable_account_id = dto.receivable_account_id;
        self.cash_account_id = dto.cash_account_id;
        self.write_off_account_id = dto.write_off_account_id;
        self.tax_account_id = dto.tax_account_id;
        self.tax_rate = dto.tax_rate;
        self.warehouse_id = dto.warehouse_id;
        self.cogs_account_id = dto.cogs_account_id;
        self.inventory_account_id = dto.inventory_account_id;
        self.allow_discount = dto.allow_discount;
        self.is_active = dto.is_active;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to PosProfile here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
