//! PosClosingEntry DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::PosClosingEntry;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::PosClosingStatus;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new PosClosingEntry
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreatePosClosingEntryDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "pos_profile_id")]
    pub pos_profile_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "opening_entry_id")]
    pub opening_entry_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "closed_at")]
    pub closed_at: DateTime<Utc>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "cashier_party_id")]
    pub cashier_party_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "totals_by_method")]
    pub totals_by_method: Option<serde_json::Value>,
    #[serde(alias = "grand_total")]
    pub grand_total: Decimal,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "invoice_count")]
    pub invoice_count: i32,
    #[serde(alias = "difference_total")]
    pub difference_total: Decimal,
    pub status: PosClosingStatus,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a PosClosingEntry
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdatePosClosingEntryDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "pos_profile_id")]
    pub pos_profile_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "opening_entry_id")]
    pub opening_entry_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "closed_at")]
    pub closed_at: DateTime<Utc>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "cashier_party_id")]
    pub cashier_party_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "totals_by_method")]
    pub totals_by_method: Option<serde_json::Value>,
    #[serde(alias = "grand_total")]
    pub grand_total: Decimal,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "invoice_count")]
    pub invoice_count: i32,
    #[serde(alias = "difference_total")]
    pub difference_total: Decimal,
    pub status: PosClosingStatus,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a PosClosingEntry
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchPosClosingEntryDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "pos_profile_id")]
    pub pos_profile_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "opening_entry_id")]
    pub opening_entry_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "closed_at")]
    pub closed_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "cashier_party_id")]
    pub cashier_party_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "totals_by_method")]
    pub totals_by_method: Option<serde_json::Value>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "grand_total")]
    pub grand_total: Option<Decimal>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "invoice_count")]
    pub invoice_count: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "difference_total")]
    pub difference_total: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<PosClosingStatus>,
}

impl PatchPosClosingEntryDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.pos_profile_id.is_some() || self.opening_entry_id.is_some() || self.closed_at.is_some() || self.cashier_party_id.is_some() || self.totals_by_method.is_some() || self.grand_total.is_some() || self.invoice_count.is_some() || self.difference_total.is_some() || self.status.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for PosClosingEntry entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PosClosingEntryResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub pos_profile_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub opening_entry_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    pub closed_at: DateTime<Utc>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub cashier_party_id: Uuid,
    pub totals_by_method: Option<serde_json::Value>,
    pub grand_total: Decimal,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub invoice_count: i32,
    pub difference_total: Decimal,
    pub status: PosClosingStatus,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for PosClosingEntry entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PosClosingEntryListResponseDto {
    /// List of items
    pub items: Vec<PosClosingEntryResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl PosClosingEntryListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<PosClosingEntryResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PosClosingEntrySummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub pos_profile_id: Uuid,
    pub opening_entry_id: Uuid,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<PosClosingEntry> for PosClosingEntryResponseDto {
    fn from(entity: PosClosingEntry) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            pos_profile_id: entity.pos_profile_id,
            opening_entry_id: entity.opening_entry_id,
            closed_at: entity.closed_at,
            cashier_party_id: entity.cashier_party_id,
            totals_by_method: entity.totals_by_method,
            grand_total: entity.grand_total,
            invoice_count: entity.invoice_count,
            difference_total: entity.difference_total,
            status: entity.status,
            metadata: entity.metadata,
        }
    }
}

impl From<PosClosingEntry> for PosClosingEntrySummaryDto {
    fn from(entity: PosClosingEntry) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            pos_profile_id: entity.pos_profile_id,
            opening_entry_id: entity.opening_entry_id,
            created_at,
        }
    }
}

impl From<CreatePosClosingEntryDto> for PosClosingEntry {
    fn from(dto: CreatePosClosingEntryDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            pos_profile_id: dto.pos_profile_id,
            opening_entry_id: dto.opening_entry_id,
            closed_at: dto.closed_at,
            cashier_party_id: dto.cashier_party_id,
            totals_by_method: dto.totals_by_method,
            grand_total: dto.grand_total,
            invoice_count: dto.invoice_count,
            difference_total: dto.difference_total,
            status: dto.status,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&PosClosingEntry> for PosClosingEntryResponseDto {
    fn from(entity: &PosClosingEntry) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            pos_profile_id: entity.pos_profile_id.clone(),
            opening_entry_id: entity.opening_entry_id.clone(),
            closed_at: entity.closed_at.clone(),
            cashier_party_id: entity.cashier_party_id.clone(),
            totals_by_method: entity.totals_by_method.clone(),
            grand_total: entity.grand_total.clone(),
            invoice_count: entity.invoice_count.clone(),
            difference_total: entity.difference_total.clone(),
            status: entity.status.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreatePosClosingEntryDto> for PosClosingEntry {
    fn from_create_dto(dto: CreatePosClosingEntryDto) -> backbone_core::ServiceResult<Self> {
        Ok(PosClosingEntry::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdatePosClosingEntryDto> for PosClosingEntry {
    fn apply_update(mut self, dto: UpdatePosClosingEntryDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.pos_profile_id = dto.pos_profile_id;
        self.opening_entry_id = dto.opening_entry_id;
        self.closed_at = dto.closed_at;
        self.cashier_party_id = dto.cashier_party_id;
        self.totals_by_method = dto.totals_by_method;
        self.grand_total = dto.grand_total;
        self.invoice_count = dto.invoice_count;
        self.difference_total = dto.difference_total;
        self.status = dto.status;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to PosClosingEntry here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
