//! Domain specifications
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Combinators (AND/OR/NOT) come from `backbone_core::Specification`.

pub use backbone_core::{Specification, AndSpecification, OrSpecification, NotSpecification};

pub mod pos_closing_entry_specification;
pub mod pos_invoice_specification;
pub mod pos_invoice_item_specification;
pub mod pos_payment_specification;
pub mod pos_profile_specification;
pub mod pos_opening_entry_specification;
pub mod pos_cash_movement_specification;

// <<< CUSTOM
// END CUSTOM
