//! Domain policies
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod pos_closing_entry_domain_policy;
pub mod pos_invoice_domain_policy;
pub mod pos_invoice_item_domain_policy;
pub mod pos_payment_domain_policy;
pub mod pos_profile_domain_policy;
pub mod pos_opening_entry_domain_policy;
pub mod pos_cash_movement_domain_policy;
pub mod pos_discount_domain_policy;
pub mod pos_manager_pin_domain_policy;
pub mod pos_floor_plan_domain_policy;
pub mod pos_table_domain_policy;

pub use pos_closing_entry_domain_policy::PosClosingEntryDomainPolicy;
pub use pos_invoice_domain_policy::PosInvoiceDomainPolicy;
pub use pos_invoice_item_domain_policy::PosInvoiceItemDomainPolicy;
pub use pos_payment_domain_policy::PosPaymentDomainPolicy;
pub use pos_profile_domain_policy::PosProfileDomainPolicy;
pub use pos_opening_entry_domain_policy::PosOpeningEntryDomainPolicy;
pub use pos_cash_movement_domain_policy::PosCashMovementDomainPolicy;
pub use pos_discount_domain_policy::PosDiscountDomainPolicy;
pub use pos_manager_pin_domain_policy::PosManagerPinDomainPolicy;
pub use pos_floor_plan_domain_policy::PosFloorPlanDomainPolicy;
pub use pos_table_domain_policy::PosTableDomainPolicy;

// <<< CUSTOM
// END CUSTOM
