//! Domain policy for PosInvoiceItem aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! `DomainPolicy` enforces pure business invariants (state-based rules).
//! Identity-based rules live in `backbone_auth::ResourcePolicy`.

use backbone_core::PermitAllPolicy;
use crate::domain::entity::PosInvoiceItem;

/// Domain policy for PosInvoiceItem — permits all operations (no business invariants).
///
/// To add domain rules, replace this alias with a struct implementing
/// `backbone_core::DomainPolicy<PosInvoiceItem>` in the `// <<< CUSTOM` zone.
pub type PosInvoiceItemDomainPolicy = PermitAllPolicy<PosInvoiceItem>;

// <<< CUSTOM
// END CUSTOM
