//! Domain policy for PosPayment aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! `DomainPolicy` enforces pure business invariants (state-based rules).
//! Identity-based rules live in `backbone_auth::ResourcePolicy`.

use backbone_core::PermitAllPolicy;
use crate::domain::entity::PosPayment;

/// Domain policy for PosPayment — permits all operations (no business invariants).
///
/// To add domain rules, replace this alias with a struct implementing
/// `backbone_core::DomainPolicy<PosPayment>` in the `// <<< CUSTOM` zone.
pub type PosPaymentDomainPolicy = PermitAllPolicy<PosPayment>;

// <<< CUSTOM
// END CUSTOM
