//! Domain policy for PosProfile aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! `DomainPolicy` enforces pure business invariants (state-based rules).
//! Identity-based rules live in `backbone_auth::ResourcePolicy`.

use backbone_core::PermitAllPolicy;
use crate::domain::entity::PosProfile;

/// Domain policy for PosProfile — permits all operations (no business invariants).
///
/// To add domain rules, replace this alias with a struct implementing
/// `backbone_core::DomainPolicy<PosProfile>` in the `// <<< CUSTOM` zone.
pub type PosProfileDomainPolicy = PermitAllPolicy<PosProfile>;

// <<< CUSTOM
// END CUSTOM
