//! Application service for PosInvoice entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `pos_invoice_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreatePosInvoiceDto, UpdatePosInvoiceDto};
use crate::domain::entity::PosInvoice;
use crate::infrastructure::persistence::PosInvoiceRepository;

/// Application service for PosInvoice entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `pos_invoice_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct PosInvoiceServiceCustom {
///     inner: Arc<PosInvoiceService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type PosInvoiceService = GenericCrudService<
    PosInvoice,
    CreatePosInvoiceDto,
    UpdatePosInvoiceDto,
    PosInvoiceRepository,
>;

// <<< CUSTOM
// END CUSTOM
