//! Application service for PosDiscount entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `pos_discount_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreatePosDiscountDto, UpdatePosDiscountDto};
use crate::domain::entity::PosDiscount;
use crate::infrastructure::persistence::PosDiscountRepository;

/// Application service for PosDiscount entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `pos_discount_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct PosDiscountServiceCustom {
///     inner: Arc<PosDiscountService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type PosDiscountService = GenericCrudService<
    PosDiscount,
    CreatePosDiscountDto,
    UpdatePosDiscountDto,
    PosDiscountRepository,
>;

// <<< CUSTOM
// END CUSTOM
