//! Application service for PosTable entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `pos_table_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreatePosTableDto, UpdatePosTableDto};
use crate::domain::entity::PosTable;
use crate::infrastructure::persistence::PosTableRepository;

/// Application service for PosTable entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `pos_table_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct PosTableServiceCustom {
///     inner: Arc<PosTableService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type PosTableService = GenericCrudService<
    PosTable,
    CreatePosTableDto,
    UpdatePosTableDto,
    PosTableRepository,
>;

// <<< CUSTOM
// END CUSTOM
