//! Application service for PosClosingEntry entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `pos_closing_entry_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreatePosClosingEntryDto, UpdatePosClosingEntryDto};
use crate::domain::entity::PosClosingEntry;
use crate::infrastructure::persistence::PosClosingEntryRepository;

/// Application service for PosClosingEntry entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `pos_closing_entry_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct PosClosingEntryServiceCustom {
///     inner: Arc<PosClosingEntryService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type PosClosingEntryService = GenericCrudService<
    PosClosingEntry,
    CreatePosClosingEntryDto,
    UpdatePosClosingEntryDto,
    PosClosingEntryRepository,
>;

// <<< CUSTOM
// END CUSTOM
