-- PosProfile Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the pos.pos_profiles table.
-- Customize this file to add your initial data.

-- INSERT INTO pos.pos_profiles (
--     id,
--     company_id,
--     branch_id,
--     name,
--     default_customer_id,
--     currency,
--     income_account_id,
--     receivable_account_id,
--     cash_account_id,
--     write_off_account_id,
--     tax_account_id,
--     tax_rate,
--     warehouse_id,
--     cogs_account_id,
--     inventory_account_id,
--     allow_discount,
--     is_active,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert reference data
-- Uncomment and modify the following:

-- INSERT INTO pos.pos_profiles (id, code, name, is_active, created_at, updated_at) VALUES
--     (gen_random_uuid(), 'SAMPLE1', 'Sample 1', true, NOW(), NOW()),
--     (gen_random_uuid(), 'SAMPLE2', 'Sample 2', true, NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

