-- PosInvoiceItem Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the pos.pos_invoice_items table.
-- Customize this file to add your initial data.

-- INSERT INTO pos.pos_invoice_items (
--     id,
--     pos_invoice_id,
--     item_id,
--     description,
--     quantity,
--     unit_price,
--     discount_amount,
--     net_amount,
--     revenue_account_id,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO pos.pos_invoice_items (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

