-- PosCashMovement Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the pos.pos_cash_movements table.
-- Customize this file to add your initial data.

-- INSERT INTO pos.pos_cash_movements (
--     id,
--     company_id,
--     pos_profile_id,
--     opening_entry_id,
--     cashier_party_id,
--     movement_type,
--     amount,
--     reason,
--     moved_at,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO pos.pos_cash_movements (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

