-- PosPayment Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the pos.pos_payments table.
-- Customize this file to add your initial data.

-- INSERT INTO pos.pos_payments (
--     id,
--     pos_invoice_id,
--     payment_method,
--     amount,
--     reference_no,
--     payment_entry_id,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO pos.pos_payments (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

