-- PosClosingEntry Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the pos.pos_closing_entries table.
-- Customize this file to add your initial data.

-- INSERT INTO pos.pos_closing_entries (
--     id,
--     company_id,
--     pos_profile_id,
--     opening_entry_id,
--     closed_at,
--     cashier_party_id,
--     totals_by_method,
--     grand_total,
--     invoice_count,
--     difference_total,
--     status,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO pos.pos_closing_entries (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

