-- PosOpeningEntry Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the pos.pos_opening_entries table.
-- Customize this file to add your initial data.

-- INSERT INTO pos.pos_opening_entries (
--     id,
--     company_id,
--     pos_profile_id,
--     branch_id,
--     cashier_party_id,
--     opened_at,
--     opening_balances,
--     status,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO pos.pos_opening_entries (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

