-- PosManagerPin Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the pos.pos_manager_pins table.
-- Customize this file to add your initial data.

-- INSERT INTO pos.pos_manager_pins (
--     id,
--     company_id,
--     employee_party_id,
--     pin_hash,
--     failed_attempts,
--     locked_until,
--     last_attempt_at,
--     last_attempt_ip,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO pos.pos_manager_pins (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

