-- Migration: Create pos_invoices table
-- Generated by metaphor-schema

-- Create pos_invoice_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'pos_invoice_status') THEN
        CREATE TYPE pos_invoice_status AS ENUM ('draft', 'paid', 'consolidated', 'returned', 'void');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS pos;

CREATE TABLE IF NOT EXISTS pos.pos_invoices (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    pos_profile_id UUID NOT NULL,
    opening_entry_id UUID NOT NULL,
    branch_id UUID,
    customer_id UUID,
    receipt_number TEXT NOT NULL,
    posting_at TIMESTAMPTZ NOT NULL,
    net_total NUMERIC NOT NULL DEFAULT 0,
    tax_total NUMERIC NOT NULL DEFAULT 0,
    grand_total NUMERIC NOT NULL DEFAULT 0,
    rounding_adjustment NUMERIC NOT NULL DEFAULT 0,
    rounded_total NUMERIC NOT NULL DEFAULT 0,
    paid_total NUMERIC NOT NULL DEFAULT 0,
    change_due NUMERIC NOT NULL DEFAULT 0,
    billing_invoice_id UUID,
    is_return BOOLEAN NOT NULL DEFAULT FALSE,
    return_against UUID,
    status pos_invoice_status NOT NULL DEFAULT 'draft',
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_pos_invoices_receipt_number ON pos.pos_invoices (receipt_number) WHERE (metadata->>'deleted_at') IS NULL;

CREATE INDEX IF NOT EXISTS idx_pos_invoices_company_id_opening_entry_id_status ON pos.pos_invoices (company_id, opening_entry_id, status);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_pos_invoices_metadata_gin ON pos.pos_invoices USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_pos_invoices_metadata_deleted_at ON pos.pos_invoices ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_pos_invoices_metadata_created_at ON pos.pos_invoices ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_pos_invoices_metadata_updated_at ON pos.pos_invoices ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION pos.pos_invoices_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS pos_invoices_insert_audit ON pos.pos_invoices;
CREATE TRIGGER pos_invoices_insert_audit BEFORE INSERT ON pos.pos_invoices
    FOR EACH ROW EXECUTE FUNCTION pos.pos_invoices_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS pos_invoices_update_audit ON pos.pos_invoices;
CREATE TRIGGER pos_invoices_update_audit BEFORE UPDATE ON pos.pos_invoices
    FOR EACH ROW EXECUTE FUNCTION pos.pos_invoices_audit_timestamp();
