-- Migration: Create pos_invoice_items table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS pos;

CREATE TABLE IF NOT EXISTS pos.pos_invoice_items (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    pos_invoice_id UUID NOT NULL,
    item_id UUID NOT NULL,
    description TEXT,
    quantity NUMERIC(18, 4) NOT NULL CHECK (quantity >= 0),
    unit_price NUMERIC(18, 2) NOT NULL CHECK (unit_price >= 0),
    discount_amount NUMERIC(18, 2) NOT NULL DEFAULT 0 CHECK (discount_amount >= 0),
    net_amount NUMERIC(18, 2) NOT NULL DEFAULT 0 CHECK (net_amount >= 0),
    revenue_account_id UUID,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_pos_invoice_items_pos_invoice_id ON pos.pos_invoice_items (pos_invoice_id);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_pos_invoice_items_metadata_gin ON pos.pos_invoice_items USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_pos_invoice_items_metadata_deleted_at ON pos.pos_invoice_items ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_pos_invoice_items_metadata_created_at ON pos.pos_invoice_items ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_pos_invoice_items_metadata_updated_at ON pos.pos_invoice_items ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION pos.pos_invoice_items_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS pos_invoice_items_insert_audit ON pos.pos_invoice_items;
CREATE TRIGGER pos_invoice_items_insert_audit BEFORE INSERT ON pos.pos_invoice_items
    FOR EACH ROW EXECUTE FUNCTION pos.pos_invoice_items_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS pos_invoice_items_update_audit ON pos.pos_invoice_items;
CREATE TRIGGER pos_invoice_items_update_audit BEFORE UPDATE ON pos.pos_invoice_items
    FOR EACH ROW EXECUTE FUNCTION pos.pos_invoice_items_audit_timestamp();
