-- Audit Triggers Migration for pos module
-- Generated by metaphor-schema
--
-- This migration adds automatic timestamp management triggers
-- to all tables with audit metadata fields.
--
-- Triggers automatically set:
--   - metadata->'created_at' on INSERT
--   - metadata->'updated_at' on INSERT and UPDATE

-- ==============================================================================
-- Table: PosClosingEntry (pos.pos_closing_entries)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION pos.pos_closing_entries_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS pos_closing_entries_insert_audit ON pos.pos_closing_entries;
CREATE TRIGGER pos_closing_entries_insert_audit BEFORE INSERT ON pos.pos_closing_entries
    FOR EACH ROW EXECUTE FUNCTION pos.pos_closing_entries_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS pos_closing_entries_update_audit ON pos.pos_closing_entries;
CREATE TRIGGER pos_closing_entries_update_audit BEFORE UPDATE ON pos.pos_closing_entries
    FOR EACH ROW EXECUTE FUNCTION pos.pos_closing_entries_audit_timestamp();

-- ==============================================================================
-- Table: PosInvoice (pos.pos_invoices)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION pos.pos_invoices_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS pos_invoices_insert_audit ON pos.pos_invoices;
CREATE TRIGGER pos_invoices_insert_audit BEFORE INSERT ON pos.pos_invoices
    FOR EACH ROW EXECUTE FUNCTION pos.pos_invoices_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS pos_invoices_update_audit ON pos.pos_invoices;
CREATE TRIGGER pos_invoices_update_audit BEFORE UPDATE ON pos.pos_invoices
    FOR EACH ROW EXECUTE FUNCTION pos.pos_invoices_audit_timestamp();

-- ==============================================================================
-- Table: PosInvoiceItem (pos.pos_invoice_items)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION pos.pos_invoice_items_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS pos_invoice_items_insert_audit ON pos.pos_invoice_items;
CREATE TRIGGER pos_invoice_items_insert_audit BEFORE INSERT ON pos.pos_invoice_items
    FOR EACH ROW EXECUTE FUNCTION pos.pos_invoice_items_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS pos_invoice_items_update_audit ON pos.pos_invoice_items;
CREATE TRIGGER pos_invoice_items_update_audit BEFORE UPDATE ON pos.pos_invoice_items
    FOR EACH ROW EXECUTE FUNCTION pos.pos_invoice_items_audit_timestamp();

-- ==============================================================================
-- Table: PosPayment (pos.pos_payments)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION pos.pos_payments_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS pos_payments_insert_audit ON pos.pos_payments;
CREATE TRIGGER pos_payments_insert_audit BEFORE INSERT ON pos.pos_payments
    FOR EACH ROW EXECUTE FUNCTION pos.pos_payments_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS pos_payments_update_audit ON pos.pos_payments;
CREATE TRIGGER pos_payments_update_audit BEFORE UPDATE ON pos.pos_payments
    FOR EACH ROW EXECUTE FUNCTION pos.pos_payments_audit_timestamp();

-- ==============================================================================
-- Table: PosProfile (pos.pos_profiles)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION pos.pos_profiles_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS pos_profiles_insert_audit ON pos.pos_profiles;
CREATE TRIGGER pos_profiles_insert_audit BEFORE INSERT ON pos.pos_profiles
    FOR EACH ROW EXECUTE FUNCTION pos.pos_profiles_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS pos_profiles_update_audit ON pos.pos_profiles;
CREATE TRIGGER pos_profiles_update_audit BEFORE UPDATE ON pos.pos_profiles
    FOR EACH ROW EXECUTE FUNCTION pos.pos_profiles_audit_timestamp();

-- ==============================================================================
-- Table: PosOpeningEntry (pos.pos_opening_entries)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION pos.pos_opening_entries_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS pos_opening_entries_insert_audit ON pos.pos_opening_entries;
CREATE TRIGGER pos_opening_entries_insert_audit BEFORE INSERT ON pos.pos_opening_entries
    FOR EACH ROW EXECUTE FUNCTION pos.pos_opening_entries_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS pos_opening_entries_update_audit ON pos.pos_opening_entries;
CREATE TRIGGER pos_opening_entries_update_audit BEFORE UPDATE ON pos.pos_opening_entries
    FOR EACH ROW EXECUTE FUNCTION pos.pos_opening_entries_audit_timestamp();

-- ==============================================================================
-- Table: PosCashMovement (pos.pos_cash_movements)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION pos.pos_cash_movements_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS pos_cash_movements_insert_audit ON pos.pos_cash_movements;
CREATE TRIGGER pos_cash_movements_insert_audit BEFORE INSERT ON pos.pos_cash_movements
    FOR EACH ROW EXECUTE FUNCTION pos.pos_cash_movements_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS pos_cash_movements_update_audit ON pos.pos_cash_movements;
CREATE TRIGGER pos_cash_movements_update_audit BEFORE UPDATE ON pos.pos_cash_movements
    FOR EACH ROW EXECUTE FUNCTION pos.pos_cash_movements_audit_timestamp();

