-- Enum types for pos module
-- Generated by metaphor-schema

-- Create pos_closing_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'pos_closing_status') THEN
        CREATE TYPE pos_closing_status AS ENUM ('draft', 'submitted', 'reconciled');
    END IF;
END
$$;

-- Create pos_invoice_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'pos_invoice_status') THEN
        CREATE TYPE pos_invoice_status AS ENUM ('draft', 'paid', 'consolidated', 'returned', 'void');
    END IF;
END
$$;

-- Create pos_payment_method enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'pos_payment_method') THEN
        CREATE TYPE pos_payment_method AS ENUM ('cash', 'card', 'qris', 'e_wallet', 'bank_transfer', 'virtual_account');
    END IF;
END
$$;

-- Create pos_session_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'pos_session_status') THEN
        CREATE TYPE pos_session_status AS ENUM ('open', 'closed');
    END IF;
END
$$;

-- Create pos_cash_movement_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'pos_cash_movement_type') THEN
        CREATE TYPE pos_cash_movement_type AS ENUM ('pay_in', 'pay_out', 'drop', 'no_sale');
    END IF;
END
$$;

