-- Add payment_entry_id to pos.pos_invoices (ADR-001 addendum 2026-07-14).
--
-- Persists the settling PaymentEntry on the ticket at recognition so a return can refund the tender
-- via the RefundRequest contract instead of a cross-schema read of payment.payment_allocations.
-- Idempotent: a full `metaphor schema generate --force` reproduces this column on the CREATE TABLE,
-- and this ALTER is a no-op then. Hand-authored (no `Generated by metaphor-schema` marker) so the
-- regen sweep preserves it.

ALTER TABLE pos.pos_invoices ADD COLUMN IF NOT EXISTS payment_entry_id UUID;
