-- Company RLS fence for pos module (ADR-0008)
-- Generated by metaphor-schema. Requires the app to connect as a
-- non-superuser role; migrations/seeders run as the owner and bypass.

-- Migration: company row-level-security fence for pos.pos_closing_entries
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE pos.pos_closing_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE pos.pos_closing_entries FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS pos_closing_entries_company_isolation ON pos.pos_closing_entries;
CREATE POLICY pos_closing_entries_company_isolation ON pos.pos_closing_entries
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for pos.pos_invoices
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE pos.pos_invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE pos.pos_invoices FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS pos_invoices_company_isolation ON pos.pos_invoices;
CREATE POLICY pos_invoices_company_isolation ON pos.pos_invoices
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for pos.pos_invoice_items
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE pos.pos_invoice_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE pos.pos_invoice_items FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS pos_invoice_items_company_isolation ON pos.pos_invoice_items;
CREATE POLICY pos_invoice_items_company_isolation ON pos.pos_invoice_items
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for pos.pos_payments
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE pos.pos_payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE pos.pos_payments FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS pos_payments_company_isolation ON pos.pos_payments;
CREATE POLICY pos_payments_company_isolation ON pos.pos_payments
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for pos.pos_profiles
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE pos.pos_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE pos.pos_profiles FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS pos_profiles_company_isolation ON pos.pos_profiles;
CREATE POLICY pos_profiles_company_isolation ON pos.pos_profiles
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for pos.pos_opening_entries
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE pos.pos_opening_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE pos.pos_opening_entries FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS pos_opening_entries_company_isolation ON pos.pos_opening_entries;
CREATE POLICY pos_opening_entries_company_isolation ON pos.pos_opening_entries
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for pos.pos_cash_movements
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE pos.pos_cash_movements ENABLE ROW LEVEL SECURITY;
ALTER TABLE pos.pos_cash_movements FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS pos_cash_movements_company_isolation ON pos.pos_cash_movements;
CREATE POLICY pos_cash_movements_company_isolation ON pos.pos_cash_movements
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

