-- Migration: Create pos_profiles table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS pos;

CREATE TABLE IF NOT EXISTS pos.pos_profiles (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    branch_id UUID,
    name TEXT NOT NULL,
    default_customer_id UUID,
    currency TEXT NOT NULL DEFAULT 'IDR',
    income_account_id UUID,
    receivable_account_id UUID,
    cash_account_id UUID,
    write_off_account_id UUID,
    allow_discount BOOLEAN NOT NULL DEFAULT TRUE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_pos_profiles_company_id_is_active ON pos.pos_profiles (company_id, is_active);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_pos_profiles_metadata_gin ON pos.pos_profiles USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_pos_profiles_metadata_deleted_at ON pos.pos_profiles ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_pos_profiles_metadata_created_at ON pos.pos_profiles ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_pos_profiles_metadata_updated_at ON pos.pos_profiles ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION pos.pos_profiles_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS pos_profiles_insert_audit ON pos.pos_profiles;
CREATE TRIGGER pos_profiles_insert_audit BEFORE INSERT ON pos.pos_profiles
    FOR EACH ROW EXECUTE FUNCTION pos.pos_profiles_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS pos_profiles_update_audit ON pos.pos_profiles;
CREATE TRIGGER pos_profiles_update_audit BEFORE UPDATE ON pos.pos_profiles
    FOR EACH ROW EXECUTE FUNCTION pos.pos_profiles_audit_timestamp();
