-- Migration: Create pos_floor_plans table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS pos;

CREATE TABLE IF NOT EXISTS pos.pos_floor_plans (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    branch_id UUID,
    name TEXT NOT NULL,
    position INTEGER,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_pos_floor_plans_company_id_branch_id ON pos.pos_floor_plans (company_id, branch_id);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_pos_floor_plans_metadata_gin ON pos.pos_floor_plans USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_pos_floor_plans_metadata_deleted_at ON pos.pos_floor_plans ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_pos_floor_plans_metadata_created_at ON pos.pos_floor_plans ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_pos_floor_plans_metadata_updated_at ON pos.pos_floor_plans ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION pos.pos_floor_plans_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS pos_floor_plans_insert_audit ON pos.pos_floor_plans;
CREATE TRIGGER pos_floor_plans_insert_audit BEFORE INSERT ON pos.pos_floor_plans
    FOR EACH ROW EXECUTE FUNCTION pos.pos_floor_plans_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS pos_floor_plans_update_audit ON pos.pos_floor_plans;
CREATE TRIGGER pos_floor_plans_update_audit BEFORE UPDATE ON pos.pos_floor_plans
    FOR EACH ROW EXECUTE FUNCTION pos.pos_floor_plans_audit_timestamp();
