//! Event handler trait for PosPayment events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::PosPaymentEvent;

/// Event handler for PosPayment events.
/// Implement this trait to react to PosPayment lifecycle events.
pub trait PosPaymentEventHandler: EventHandler<PosPaymentEvent> {}
