//! Domain events for PosDiscount entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::PosDiscount;

/// Domain events for PosDiscount — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<PosDiscount>)` variant.
pub type PosDiscountEvent = CrudEvent<PosDiscount>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for PosDiscount events.
pub type PosDiscountEventPublisher = Arc<dyn CrudEventPublisher<PosDiscount> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopPosDiscountEventPublisher = NoOpCrudEventPublisher<PosDiscount>;
