//! Event handler trait for PosInvoice events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::PosInvoiceEvent;

/// Event handler for PosInvoice events.
/// Implement this trait to react to PosInvoice lifecycle events.
pub trait PosInvoiceEventHandler: EventHandler<PosInvoiceEvent> {}
