//! Domain events for PosClosingEntry entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::PosClosingEntry;

/// Domain events for PosClosingEntry — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<PosClosingEntry>)` variant.
pub type PosClosingEntryEvent = CrudEvent<PosClosingEntry>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for PosClosingEntry events.
pub type PosClosingEntryEventPublisher = Arc<dyn CrudEventPublisher<PosClosingEntry> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopPosClosingEntryEventPublisher = NoOpCrudEventPublisher<PosClosingEntry>;
