//! Domain events for PosCashMovement entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::PosCashMovement;

/// Domain events for PosCashMovement — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<PosCashMovement>)` variant.
pub type PosCashMovementEvent = CrudEvent<PosCashMovement>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for PosCashMovement events.
pub type PosCashMovementEventPublisher = Arc<dyn CrudEventPublisher<PosCashMovement> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopPosCashMovementEventPublisher = NoOpCrudEventPublisher<PosCashMovement>;
