//! Domain events for PosPayment entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::PosPayment;

/// Domain events for PosPayment — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<PosPayment>)` variant.
pub type PosPaymentEvent = CrudEvent<PosPayment>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for PosPayment events.
pub type PosPaymentEventPublisher = Arc<dyn CrudEventPublisher<PosPayment> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopPosPaymentEventPublisher = NoOpCrudEventPublisher<PosPayment>;
