//! Domain events for PosTable entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::PosTable;

/// Domain events for PosTable — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<PosTable>)` variant.
pub type PosTableEvent = CrudEvent<PosTable>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for PosTable events.
pub type PosTableEventPublisher = Arc<dyn CrudEventPublisher<PosTable> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopPosTableEventPublisher = NoOpCrudEventPublisher<PosTable>;
