//! Event handler trait for PosProfile events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::PosProfileEvent;

/// Event handler for PosProfile events.
/// Implement this trait to react to PosProfile lifecycle events.
pub trait PosProfileEventHandler: EventHandler<PosProfileEvent> {}
