//! Domain events for PosManagerPin entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::PosManagerPin;

/// Domain events for PosManagerPin — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<PosManagerPin>)` variant.
pub type PosManagerPinEvent = CrudEvent<PosManagerPin>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for PosManagerPin events.
pub type PosManagerPinEventPublisher = Arc<dyn CrudEventPublisher<PosManagerPin> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopPosManagerPinEventPublisher = NoOpCrudEventPublisher<PosManagerPin>;
