//! Event handler trait for PosTable events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::PosTableEvent;

/// Event handler for PosTable events.
/// Implement this trait to react to PosTable lifecycle events.
pub trait PosTableEventHandler: EventHandler<PosTableEvent> {}
