//! Event handler trait for PosFloorPlan events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::PosFloorPlanEvent;

/// Event handler for PosFloorPlan events.
/// Implement this trait to react to PosFloorPlan lifecycle events.
pub trait PosFloorPlanEventHandler: EventHandler<PosFloorPlanEvent> {}
