//! Event subscriber type aliases for Pos module
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::GenericEventSubscriber;

use crate::domain::event::PosClosingEntryEvent;
use crate::domain::event::PosInvoiceEvent;
use crate::domain::event::PosInvoiceItemEvent;
use crate::domain::event::PosPaymentEvent;
use crate::domain::event::PosProfileEvent;
use crate::domain::event::PosOpeningEntryEvent;

/// Subscriber for PosClosingEntry events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type PosClosingEntryEventSubscriber = GenericEventSubscriber<PosClosingEntryEvent>;

/// Subscriber for PosInvoice events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type PosInvoiceEventSubscriber = GenericEventSubscriber<PosInvoiceEvent>;

/// Subscriber for PosInvoiceItem events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type PosInvoiceItemEventSubscriber = GenericEventSubscriber<PosInvoiceItemEvent>;

/// Subscriber for PosPayment events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type PosPaymentEventSubscriber = GenericEventSubscriber<PosPaymentEvent>;

/// Subscriber for PosProfile events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type PosProfileEventSubscriber = GenericEventSubscriber<PosProfileEvent>;

/// Subscriber for PosOpeningEntry events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type PosOpeningEntryEventSubscriber = GenericEventSubscriber<PosOpeningEntryEvent>;

// <<< CUSTOM
// END CUSTOM
