//! PosFloorPlan seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial PosFloorPlan data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// POSFLOORPLAN SEEDER
// ============================================================================

/// Seeder for pos_floor_plan
pub struct SeedPosFloorPlanSeeder;

impl SeedPosFloorPlanSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedPosFloorPlanSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedPosFloorPlanSeeder {
    fn name(&self) -> &'static str {
        "SeedPosFloorPlanSeeder"
    }

    fn order(&self) -> i32 {
        10
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if pos.pos_floor_plans table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM pos.pos_floor_plans")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/pos_floor_plan_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM pos.pos_floor_plans")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>
