//! PosProfile seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial PosProfile data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// POSPROFILE SEEDER
// ============================================================================

/// Seeder for pos_profile
pub struct SeedPosProfileSeeder;

impl SeedPosProfileSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedPosProfileSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedPosProfileSeeder {
    fn name(&self) -> &'static str {
        "SeedPosProfileSeeder"
    }

    fn order(&self) -> i32 {
        5
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if pos.pos_profiles table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM pos.pos_profiles")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/pos_profile_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM pos.pos_profiles")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>
