//! Repository trait for PosInvoiceItem aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the PosInvoiceItem aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::PosInvoiceItem;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct PosInvoiceItemPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl PosInvoiceItemPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct PosInvoiceItemPaginatedResult {
    pub data: Vec<PosInvoiceItem>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct PosInvoiceItemFilter {
    pub company_id: Option<Uuid>,
    pub pos_invoice_id: Option<Uuid>,
    pub item_id: Option<Uuid>,
    pub description: Option<String>,
    pub revenue_account_id: Option<Uuid>,
}

impl PosInvoiceItemFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.pos_invoice_id.is_some() || self.item_id.is_some() || self.description.is_some() || self.revenue_account_id.is_some()
    }
}

/// Repository trait for PosInvoiceItem aggregate
///
/// This trait defines the persistence contract for PosInvoiceItem entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait PosInvoiceItemRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new pos_invoice_item entity
    async fn save(&self, entity: &PosInvoiceItem) -> Result<PosInvoiceItem>;

    /// Find pos_invoice_item by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<PosInvoiceItem>>;

    /// Find all pos_invoice_item entities
    async fn find_all(&self) -> Result<Vec<PosInvoiceItem>>;

    /// Update pos_invoice_item by ID
    async fn update(&self, id: &str, entity: &PosInvoiceItem) -> Result<Option<PosInvoiceItem>>;

    /// Delete pos_invoice_item by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List pos_invoice_item with pagination
    async fn list(&self, params: PosInvoiceItemPaginationParams) -> Result<PosInvoiceItemPaginatedResult>;

    /// List pos_invoice_item with pagination and filters
    async fn list_with_filters(&self, params: PosInvoiceItemPaginationParams, filters: PosInvoiceItemFilter) -> Result<PosInvoiceItemPaginatedResult>;

    /// Count all pos_invoice_item entities
    async fn count(&self) -> Result<u64>;

    /// Count pos_invoice_item entities matching filters
    async fn count_with_filters(&self, filters: PosInvoiceItemFilter) -> Result<u64>;

    /// Check if pos_invoice_item exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete pos_invoice_item by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted pos_invoice_item by ID
    async fn restore(&self, id: &str) -> Result<Option<PosInvoiceItem>>;

    /// List soft-deleted pos_invoice_item entities
    async fn list_deleted(&self, params: PosInvoiceItemPaginationParams) -> Result<PosInvoiceItemPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save pos_invoice_item entities
    async fn bulk_save(&self, entities: &[PosInvoiceItem]) -> Result<Vec<PosInvoiceItem>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
