//! Repository trait for PosFloorPlan aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the PosFloorPlan aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::PosFloorPlan;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct PosFloorPlanPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl PosFloorPlanPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct PosFloorPlanPaginatedResult {
    pub data: Vec<PosFloorPlan>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct PosFloorPlanFilter {
    pub company_id: Option<Uuid>,
    pub branch_id: Option<Uuid>,
    pub name: Option<String>,
}

impl PosFloorPlanFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.branch_id.is_some() || self.name.is_some()
    }
}

/// Repository trait for PosFloorPlan aggregate
///
/// This trait defines the persistence contract for PosFloorPlan entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait PosFloorPlanRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new pos_floor_plan entity
    async fn save(&self, entity: &PosFloorPlan) -> Result<PosFloorPlan>;

    /// Find pos_floor_plan by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<PosFloorPlan>>;

    /// Find all pos_floor_plan entities
    async fn find_all(&self) -> Result<Vec<PosFloorPlan>>;

    /// Update pos_floor_plan by ID
    async fn update(&self, id: &str, entity: &PosFloorPlan) -> Result<Option<PosFloorPlan>>;

    /// Delete pos_floor_plan by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List pos_floor_plan with pagination
    async fn list(&self, params: PosFloorPlanPaginationParams) -> Result<PosFloorPlanPaginatedResult>;

    /// List pos_floor_plan with pagination and filters
    async fn list_with_filters(&self, params: PosFloorPlanPaginationParams, filters: PosFloorPlanFilter) -> Result<PosFloorPlanPaginatedResult>;

    /// Count all pos_floor_plan entities
    async fn count(&self) -> Result<u64>;

    /// Count pos_floor_plan entities matching filters
    async fn count_with_filters(&self, filters: PosFloorPlanFilter) -> Result<u64>;

    /// Check if pos_floor_plan exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete pos_floor_plan by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted pos_floor_plan by ID
    async fn restore(&self, id: &str) -> Result<Option<PosFloorPlan>>;

    /// List soft-deleted pos_floor_plan entities
    async fn list_deleted(&self, params: PosFloorPlanPaginationParams) -> Result<PosFloorPlanPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save pos_floor_plan entities
    async fn bulk_save(&self, entities: &[PosFloorPlan]) -> Result<Vec<PosFloorPlan>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
