//! Repository trait for PosInvoice aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the PosInvoice aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{PosInvoice, PosInvoiceStatus};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct PosInvoicePaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl PosInvoicePaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct PosInvoicePaginatedResult {
    pub data: Vec<PosInvoice>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct PosInvoiceFilter {
    pub company_id: Option<Uuid>,
    pub pos_profile_id: Option<Uuid>,
    pub opening_entry_id: Option<Uuid>,
    pub branch_id: Option<Uuid>,
    pub customer_id: Option<Uuid>,
    pub receipt_number: Option<String>,
    pub billing_invoice_id: Option<Uuid>,
    pub is_return: Option<bool>,
    pub return_against: Option<Uuid>,
    pub status: Option<PosInvoiceStatus>,
}

impl PosInvoiceFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.pos_profile_id.is_some() || self.opening_entry_id.is_some() || self.branch_id.is_some() || self.customer_id.is_some() || self.receipt_number.is_some() || self.billing_invoice_id.is_some() || self.is_return.is_some() || self.return_against.is_some() || self.status.is_some()
    }
}

/// Repository trait for PosInvoice aggregate
///
/// This trait defines the persistence contract for PosInvoice entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait PosInvoiceRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new pos_invoice entity
    async fn save(&self, entity: &PosInvoice) -> Result<PosInvoice>;

    /// Find pos_invoice by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<PosInvoice>>;

    /// Find all pos_invoice entities
    async fn find_all(&self) -> Result<Vec<PosInvoice>>;

    /// Update pos_invoice by ID
    async fn update(&self, id: &str, entity: &PosInvoice) -> Result<Option<PosInvoice>>;

    /// Delete pos_invoice by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List pos_invoice with pagination
    async fn list(&self, params: PosInvoicePaginationParams) -> Result<PosInvoicePaginatedResult>;

    /// List pos_invoice with pagination and filters
    async fn list_with_filters(&self, params: PosInvoicePaginationParams, filters: PosInvoiceFilter) -> Result<PosInvoicePaginatedResult>;

    /// Count all pos_invoice entities
    async fn count(&self) -> Result<u64>;

    /// Count pos_invoice entities matching filters
    async fn count_with_filters(&self, filters: PosInvoiceFilter) -> Result<u64>;

    /// Check if pos_invoice exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete pos_invoice by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted pos_invoice by ID
    async fn restore(&self, id: &str) -> Result<Option<PosInvoice>>;

    /// List soft-deleted pos_invoice entities
    async fn list_deleted(&self, params: PosInvoicePaginationParams) -> Result<PosInvoicePaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save pos_invoice entities
    async fn bulk_save(&self, entities: &[PosInvoice]) -> Result<Vec<PosInvoice>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
