//! Repository trait for PosCashMovement aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the PosCashMovement aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{PosCashMovement, PosCashMovementType};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct PosCashMovementPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl PosCashMovementPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct PosCashMovementPaginatedResult {
    pub data: Vec<PosCashMovement>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct PosCashMovementFilter {
    pub company_id: Option<Uuid>,
    pub pos_profile_id: Option<Uuid>,
    pub opening_entry_id: Option<Uuid>,
    pub cashier_party_id: Option<Uuid>,
    pub movement_type: Option<PosCashMovementType>,
    pub reason: Option<String>,
}

impl PosCashMovementFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.pos_profile_id.is_some() || self.opening_entry_id.is_some() || self.cashier_party_id.is_some() || self.movement_type.is_some() || self.reason.is_some()
    }
}

/// Repository trait for PosCashMovement aggregate
///
/// This trait defines the persistence contract for PosCashMovement entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait PosCashMovementRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new pos_cash_movement entity
    async fn save(&self, entity: &PosCashMovement) -> Result<PosCashMovement>;

    /// Find pos_cash_movement by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<PosCashMovement>>;

    /// Find all pos_cash_movement entities
    async fn find_all(&self) -> Result<Vec<PosCashMovement>>;

    /// Update pos_cash_movement by ID
    async fn update(&self, id: &str, entity: &PosCashMovement) -> Result<Option<PosCashMovement>>;

    /// Delete pos_cash_movement by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List pos_cash_movement with pagination
    async fn list(&self, params: PosCashMovementPaginationParams) -> Result<PosCashMovementPaginatedResult>;

    /// List pos_cash_movement with pagination and filters
    async fn list_with_filters(&self, params: PosCashMovementPaginationParams, filters: PosCashMovementFilter) -> Result<PosCashMovementPaginatedResult>;

    /// Count all pos_cash_movement entities
    async fn count(&self) -> Result<u64>;

    /// Count pos_cash_movement entities matching filters
    async fn count_with_filters(&self, filters: PosCashMovementFilter) -> Result<u64>;

    /// Check if pos_cash_movement exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete pos_cash_movement by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted pos_cash_movement by ID
    async fn restore(&self, id: &str) -> Result<Option<PosCashMovement>>;

    /// List soft-deleted pos_cash_movement entities
    async fn list_deleted(&self, params: PosCashMovementPaginationParams) -> Result<PosCashMovementPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save pos_cash_movement entities
    async fn bulk_save(&self, entities: &[PosCashMovement]) -> Result<Vec<PosCashMovement>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
