//! Repository trait for PosProfile aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the PosProfile aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::PosProfile;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct PosProfilePaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl PosProfilePaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct PosProfilePaginatedResult {
    pub data: Vec<PosProfile>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct PosProfileFilter {
    pub company_id: Option<Uuid>,
    pub branch_id: Option<Uuid>,
    pub name: Option<String>,
    pub default_customer_id: Option<Uuid>,
    pub currency: Option<String>,
    pub income_account_id: Option<Uuid>,
    pub receivable_account_id: Option<Uuid>,
    pub cash_account_id: Option<Uuid>,
    pub write_off_account_id: Option<Uuid>,
    pub tax_account_id: Option<Uuid>,
    pub allow_discount: Option<bool>,
    pub is_active: Option<bool>,
}

impl PosProfileFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.branch_id.is_some() || self.name.is_some() || self.default_customer_id.is_some() || self.currency.is_some() || self.income_account_id.is_some() || self.receivable_account_id.is_some() || self.cash_account_id.is_some() || self.write_off_account_id.is_some() || self.tax_account_id.is_some() || self.allow_discount.is_some() || self.is_active.is_some()
    }
}

/// Repository trait for PosProfile aggregate
///
/// This trait defines the persistence contract for PosProfile entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait PosProfileRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new pos_profile entity
    async fn save(&self, entity: &PosProfile) -> Result<PosProfile>;

    /// Find pos_profile by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<PosProfile>>;

    /// Find all pos_profile entities
    async fn find_all(&self) -> Result<Vec<PosProfile>>;

    /// Update pos_profile by ID
    async fn update(&self, id: &str, entity: &PosProfile) -> Result<Option<PosProfile>>;

    /// Delete pos_profile by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List pos_profile with pagination
    async fn list(&self, params: PosProfilePaginationParams) -> Result<PosProfilePaginatedResult>;

    /// List pos_profile with pagination and filters
    async fn list_with_filters(&self, params: PosProfilePaginationParams, filters: PosProfileFilter) -> Result<PosProfilePaginatedResult>;

    /// Count all pos_profile entities
    async fn count(&self) -> Result<u64>;

    /// Count pos_profile entities matching filters
    async fn count_with_filters(&self, filters: PosProfileFilter) -> Result<u64>;

    /// Check if pos_profile exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete pos_profile by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted pos_profile by ID
    async fn restore(&self, id: &str) -> Result<Option<PosProfile>>;

    /// List soft-deleted pos_profile entities
    async fn list_deleted(&self, params: PosProfilePaginationParams) -> Result<PosProfilePaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save pos_profile entities
    async fn bulk_save(&self, entities: &[PosProfile]) -> Result<Vec<PosProfile>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
