//! Repository implementations
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Uses backbone-orm's `DatabaseOperations<T>` trait.

mod pos_closing_entry_repository;
mod pos_invoice_repository;
mod pos_invoice_item_repository;
mod pos_payment_repository;
mod pos_profile_repository;
mod pos_opening_entry_repository;
mod pos_cash_movement_repository;

// Custom persistence modules
// <<< CUSTOM
// END CUSTOM

// Re-exports
pub use pos_closing_entry_repository::PosClosingEntryRepository;
pub use pos_invoice_repository::PosInvoiceRepository;
pub use pos_invoice_item_repository::PosInvoiceItemRepository;
pub use pos_payment_repository::PosPaymentRepository;
pub use pos_profile_repository::PosProfileRepository;
pub use pos_opening_entry_repository::PosOpeningEntryRepository;
pub use pos_cash_movement_repository::PosCashMovementRepository;

// Re-export backbone-orm types
pub use backbone_orm::repository::{
    DatabaseOperations, PostgresRepository,
    PaginationParams, PaginationInfo, PaginatedResult,
    FilterParams, FilterCondition, SortParams, SortDirection,
};

// Re-export custom persistence types
// <<< CUSTOM
// The hand-written POS SQL's parameter/projection types. Their repositories are each declared
// `user_owned` in metaphor.codegen.yaml; the param structs mirror COLUMNS, not entities.
pub use pos_cash_movement_repository::NewCashMovementRow;
pub use pos_closing_entry_repository::NewClosingEntryRow;
pub use pos_invoice_item_repository::{
    NewInvoiceItemRow, QuantityLineRow, ReceiptLineRow, RevenueLineRow,
};
pub use pos_invoice_repository::{
    NewDraftInvoiceRow, NewReturnInvoiceRow, PaidStateRow, ReceiptHeaderRow, RecognitionRow,
    ReturnSourceRow, TenderHeaderRow,
};
pub use pos_opening_entry_repository::NewOpeningEntryRow;
pub use pos_payment_repository::{MethodTotalRow, NewTenderRow, ReceiptTenderRow};
// END CUSTOM