//! Repository for PosInvoiceItem entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written ticket-line SQL (4-layer rule: services orchestrate, repos hold SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<PosInvoiceItem, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use rust_decimal::Decimal;
use sqlx::{PgPool, Row};
use uuid::Uuid;

use backbone_orm::company_scope;

use crate::domain::entity::PosInvoiceItem;

/// Table name for PosInvoiceItem entities
pub const TABLE_NAME: &str = "pos.pos_invoice_items";

/// Repository for PosInvoiceItem entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct PosInvoiceItemRepository(
    backbone_orm::GenericCrudRepository<PosInvoiceItem, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for PosInvoiceItemRepository {
    type Target = backbone_orm::GenericCrudRepository<PosInvoiceItem, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl PosInvoiceItemRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row a ticket line writes. Mirrors the raw column shape rather than the `PosInvoiceItem`
/// entity: `net_amount` is the already-computed line net (qty x price - discount), not re-derived here.
pub struct NewInvoiceItemRow<'a> {
    pub id: Uuid,
    pub pos_invoice_id: Uuid,
    pub item_id: Uuid,
    pub description: Option<&'a str>,
    pub quantity: Decimal,
    pub unit_price: Decimal,
    pub discount_amount: Decimal,
    pub net_amount: Decimal,
    pub revenue_account_id: Option<Uuid>,
}

/// A ticket line as the billing hand-off reads it: the net to invoice + its revenue account.
pub struct RevenueLineRow {
    pub item_id: Uuid,
    pub net_amount: Decimal,
    pub revenue_account_id: Option<Uuid>,
}

/// A ticket line as the stock issue reads it: what to relieve from the warehouse.
pub struct QuantityLineRow {
    pub item_id: Uuid,
    pub quantity: Decimal,
}

/// A ticket line as the printed receipt reads it.
pub struct ReceiptLineRow {
    pub description: Option<String>,
    pub item_id: Uuid,
    pub quantity: Decimal,
    pub unit_price: Decimal,
    pub discount_amount: Decimal,
    pub net_amount: Decimal,
}

/// Hand-written ticket-line SQL. Lives here (not in the write service) per the module's 4-layer rule:
/// services orchestrate and own the unit of work, repositories hold the SQL.
impl PosInvoiceItemRepository {
    /// Insert one ticket line.
    ///
    /// Takes the CALLER'S connection so every line and its invoice header commit as one unit — a ticket
    /// is never half-rung. The caller has already bound the company on it (`bind_current_company`) —
    /// don't re-bind here.
    pub async fn insert_line(
        &self,
        conn: &mut sqlx::PgConnection,
        l: &NewInvoiceItemRow<'_>,
    ) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"INSERT INTO pos.pos_invoice_items
                (id, pos_invoice_id, item_id, description, quantity, unit_price, discount_amount, net_amount, revenue_account_id)
               VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)"#,
        )
        .bind(l.id).bind(l.pos_invoice_id).bind(l.item_id).bind(l.description).bind(l.quantity)
        .bind(l.unit_price).bind(l.discount_amount).bind(l.net_amount).bind(l.revenue_account_id)
        .execute(conn)
        .await?;
        Ok(())
    }

    /// Read the lines the billing hand-off invoices.
    ///
    /// ID-only: no company argument. `fetch_all_rows_scoped` means it rides a connection carrying the
    /// caller's `app.company_id`, so another company's lines simply are not found. A non-request caller
    /// (the recognition sink driven by `PosTenderCompleted`) MUST wrap this in
    /// `with_company_scope(Some(company_id))` — otherwise it fails closed and returns no lines.
    pub async fn fetch_revenue_lines(
        &self,
        pool: &PgPool,
        pos_invoice_id: Uuid,
    ) -> Result<Vec<RevenueLineRow>, sqlx::Error> {
        let rows = company_scope::fetch_all_rows_scoped(
            pool,
            sqlx::query(
                "SELECT item_id, net_amount, revenue_account_id FROM pos.pos_invoice_items WHERE pos_invoice_id=$1 AND (metadata->>'deleted_at') IS NULL",
            )
            .bind(pos_invoice_id),
        )
        .await?;
        Ok(rows.iter().map(|r| RevenueLineRow {
            item_id: r.get("item_id"), net_amount: r.get("net_amount"),
            revenue_account_id: r.get("revenue_account_id"),
        }).collect())
    }

    /// Read the lines the stock issue relieves. Same ID-only scope contract as
    /// [`Self::fetch_revenue_lines`].
    pub async fn fetch_quantity_lines(
        &self,
        pool: &PgPool,
        pos_invoice_id: Uuid,
    ) -> Result<Vec<QuantityLineRow>, sqlx::Error> {
        let rows = company_scope::fetch_all_rows_scoped(
            pool,
            sqlx::query(
                "SELECT item_id, quantity FROM pos.pos_invoice_items WHERE pos_invoice_id=$1 AND (metadata->>'deleted_at') IS NULL",
            )
            .bind(pos_invoice_id),
        )
        .await?;
        Ok(rows.iter().map(|r| QuantityLineRow {
            item_id: r.get("item_id"), quantity: r.get("quantity"),
        }).collect())
    }

    /// Read the lines for the printed receipt, in ring order. Same ID-only scope contract as
    /// [`Self::fetch_revenue_lines`]; the caller supplies the company scope on the parameter.
    pub async fn fetch_receipt_lines(
        &self,
        pool: &PgPool,
        pos_invoice_id: Uuid,
    ) -> Result<Vec<ReceiptLineRow>, sqlx::Error> {
        let rows = company_scope::fetch_all_rows_scoped(
            pool,
            sqlx::query(
                "SELECT description, item_id, quantity, unit_price, discount_amount, net_amount
                 FROM pos.pos_invoice_items WHERE pos_invoice_id=$1 AND (metadata->>'deleted_at') IS NULL
                 ORDER BY (metadata->>'created_at')",
            )
            .bind(pos_invoice_id),
        )
        .await?;
        Ok(rows.iter().map(|r| ReceiptLineRow {
            description: r.get("description"), item_id: r.get("item_id"), quantity: r.get("quantity"),
            unit_price: r.get("unit_price"), discount_amount: r.get("discount_amount"),
            net_amount: r.get("net_amount"),
        }).collect())
    }
}

backbone_core::impl_crud_repository!(PosInvoiceItemRepository, PosInvoiceItem, soft_delete);
