//! Repository for PosInvoice entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written counter-ticket SQL (4-layer rule: services orchestrate, repos hold SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<PosInvoice, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use rust_decimal::Decimal;
use sqlx::{PgPool, Row};
use uuid::Uuid;

use backbone_orm::company_scope;

use crate::domain::entity::PosInvoice;

/// Table name for PosInvoice entities
pub const TABLE_NAME: &str = "pos.pos_invoices";

/// Repository for PosInvoice entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct PosInvoiceRepository(
    backbone_orm::GenericCrudRepository<PosInvoice, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for PosInvoiceRepository {
    type Target = backbone_orm::GenericCrudRepository<PosInvoice, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl PosInvoiceRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row a rung ticket writes. Mirrors the raw column shape rather than the `PosInvoice`
/// entity: the money fields are already computed by the service, and `paid_total`/`change_due`/
/// `is_return`/`status` are fixed by the SQL (`0,0,false,'draft'`).
pub struct NewDraftInvoiceRow<'a> {
    pub id: Uuid,
    pub company_id: Uuid,
    pub pos_profile_id: Uuid,
    pub opening_entry_id: Uuid,
    pub branch_id: Option<Uuid>,
    pub customer_id: Option<Uuid>,
    pub receipt_number: &'a str,
    pub posting_at: chrono::NaiveDateTime,
    pub net_total: Decimal,
    pub tax_total: Decimal,
    pub grand_total: Decimal,
    pub rounding_adjustment: Decimal,
    pub rounded_total: Decimal,
}

/// The exact row a return ticket writes. Mirrors the raw column shape: the SQL fixes
/// `rounding_adjustment` to 0, binds `rounded_total` to both the rounded and paid totals ($12), fixes
/// `change_due` to 0, and fixes `is_return`/`status` to `true`/`'returned'`.
pub struct NewReturnInvoiceRow {
    pub id: Uuid,
    pub company_id: Uuid,
    pub pos_profile_id: Uuid,
    pub opening_entry_id: Uuid,
    pub branch_id: Option<Uuid>,
    pub customer_id: Option<Uuid>,
    pub receipt_number: String,
    pub posting_at: chrono::DateTime<chrono::Utc>,
    pub net_total: Decimal,
    pub tax_total: Decimal,
    pub grand_total: Decimal,
    pub rounded_total: Decimal,
    pub billing_invoice_id: Uuid,
    pub return_against: Uuid,
}

/// A ticket header as `add_tender` reads it: the draft gate, the target total, and the company to bind.
pub struct TenderHeaderRow {
    pub status: String,
    pub rounded_total: Decimal,
    pub company_id: Uuid,
}

/// A ticket's already-recognised state, as the recognise short-circuit reads it.
pub struct PaidStateRow {
    pub status: String,
    pub billing_invoice_id: Option<Uuid>,
    pub payment_entry_id: Option<Uuid>,
}

/// Everything recognition needs about a draft ticket + its register, in one read: the money to settle,
/// the accounts to post to, and the stock dimensions to relieve.
pub struct RecognitionRow {
    pub company_id: Uuid,
    pub customer_id: Option<Uuid>,
    pub branch_id: Option<Uuid>,
    pub posting_at: chrono::DateTime<chrono::Utc>,
    pub rounded_total: Decimal,
    pub grand_total: Decimal,
    pub tax_total: Decimal,
    pub paid_total: Decimal,
    pub billing_invoice_id: Option<Uuid>,
    pub receivable_account_id: Option<Uuid>,
    pub income_account_id: Option<Uuid>,
    pub cash_account_id: Option<Uuid>,
    pub tax_account_id: Option<Uuid>,
    pub tax_rate: Decimal,
    pub warehouse_id: Option<Uuid>,
    pub cogs_account_id: Option<Uuid>,
    pub inventory_account_id: Option<Uuid>,
    pub currency: String,
    pub default_customer_id: Option<Uuid>,
}

/// The original ticket as the returns path reads it — the source of every field the return ticket
/// copies, plus the tender/invoice refs to reverse.
pub struct ReturnSourceRow {
    pub company_id: Uuid,
    pub pos_profile_id: Uuid,
    pub opening_entry_id: Uuid,
    pub branch_id: Option<Uuid>,
    pub customer_id: Option<Uuid>,
    pub billing_invoice_id: Option<Uuid>,
    pub payment_entry_id: Option<Uuid>,
    pub rounded_total: Decimal,
    pub net_total: Decimal,
    pub tax_total: Decimal,
    pub grand_total: Decimal,
    pub posting_at: chrono::DateTime<chrono::Utc>,
    pub status: String,
}

/// A ticket header as the printed receipt reads it (register name/currency/rate joined in).
pub struct ReceiptHeaderRow {
    pub receipt_number: String,
    pub posting_at: chrono::DateTime<chrono::Utc>,
    pub net_total: Decimal,
    pub tax_total: Decimal,
    pub rounding_adjustment: Decimal,
    pub rounded_total: Decimal,
    pub paid_total: Decimal,
    pub change_due: Decimal,
    pub status: String,
    pub register_name: String,
    pub currency: String,
    pub tax_rate: Decimal,
}

/// Hand-written counter-ticket SQL. Lives here (not in the write service) per the module's 4-layer
/// rule: services orchestrate and own the unit of work, repositories hold the SQL.
impl PosInvoiceRepository {
    /// Insert a rung ticket in `draft`.
    ///
    /// Takes the CALLER'S connection so the header and its lines commit as one unit. The caller has
    /// already bound the company on it (`bind_current_company`) — don't re-bind here.
    ///
    /// Returns the raw `sqlx::Error` deliberately: the caller inspects it for a unique violation to turn
    /// a re-used receipt number into a domain error.
    pub async fn insert_draft(
        &self,
        conn: &mut sqlx::PgConnection,
        i: &NewDraftInvoiceRow<'_>,
    ) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"INSERT INTO pos.pos_invoices
                (id, company_id, pos_profile_id, opening_entry_id, branch_id, customer_id, receipt_number,
                 posting_at, net_total, tax_total, grand_total, rounding_adjustment, rounded_total,
                 paid_total, change_due, is_return, status)
               VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,0,0,false,'draft'::pos_invoice_status)"#,
        )
        .bind(i.id).bind(i.company_id).bind(i.pos_profile_id).bind(i.opening_entry_id).bind(i.branch_id)
        .bind(i.customer_id).bind(i.receipt_number).bind(i.posting_at).bind(i.net_total).bind(i.tax_total)
        .bind(i.grand_total).bind(i.rounding_adjustment).bind(i.rounded_total)
        .execute(conn)
        .await?;
        Ok(())
    }

    /// Read the header `add_tender` gates on.
    ///
    /// ID-only: no company argument. `fetch_optional_row_scoped` means it rides the REQUEST-dedicated
    /// connection carrying the caller's `app.company_id`, so another company's ticket simply is not
    /// found. A non-request caller MUST wrap this in `with_company_scope(Some(company_id))` — otherwise
    /// it fails closed and returns `Ok(None)`. The returned `company_id` is what the caller then binds
    /// onto its own transaction.
    pub async fn fetch_tender_header(
        &self,
        pool: &PgPool,
        pos_invoice_id: Uuid,
    ) -> Result<Option<TenderHeaderRow>, sqlx::Error> {
        let row = company_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                "SELECT status::text AS st, rounded_total, company_id FROM pos.pos_invoices WHERE id=$1 AND (metadata->>'deleted_at') IS NULL",
            )
            .bind(pos_invoice_id),
        )
        .await?;
        Ok(row.map(|r| TenderHeaderRow {
            status: r.get("st"), rounded_total: r.get("rounded_total"), company_id: r.get("company_id"),
        }))
    }

    /// Write back a ticket's recomputed tender totals. Takes the CALLER'S connection so this and the
    /// tender insert commit as one unit; the caller has already bound the company on it.
    pub async fn update_tender_totals(
        &self,
        conn: &mut sqlx::PgConnection,
        pos_invoice_id: Uuid,
        paid_total: Decimal,
        change_due: Decimal,
    ) -> Result<(), sqlx::Error> {
        sqlx::query("UPDATE pos.pos_invoices SET paid_total=$2, change_due=$3 WHERE id=$1")
            .bind(pos_invoice_id).bind(paid_total).bind(change_due)
            .execute(conn)
            .await?;
        Ok(())
    }

    /// Read a ticket's recognised state, for the recognise short-circuit. Same ID-only scope contract as
    /// [`Self::fetch_tender_header`].
    pub async fn fetch_paid_state(
        &self,
        pool: &PgPool,
        pos_invoice_id: Uuid,
    ) -> Result<Option<PaidStateRow>, sqlx::Error> {
        let row = company_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                "SELECT status::text AS st, billing_invoice_id, payment_entry_id FROM pos.pos_invoices WHERE id=$1 AND (metadata->>'deleted_at') IS NULL",
            )
            .bind(pos_invoice_id),
        )
        .await?;
        Ok(row.map(|r| PaidStateRow {
            status: r.get("st"), billing_invoice_id: r.get("billing_invoice_id"),
            payment_entry_id: r.get("payment_entry_id"),
        }))
    }

    /// Read a DRAFT ticket joined to its register — everything recognition needs to drive billing,
    /// payment, and the optional stock issue. `Ok(None)` = absent, already recognised, or another
    /// company's.
    ///
    /// ID-only: no company argument. Under HTTP the request-dedicated connection carries the scope. When
    /// driven by an EVENT (the recognition sink subscribing to `PosTenderCompleted`), the caller MUST
    /// wrap this in `with_company_scope(Some(event.company_id))` — the event carries the company —
    /// otherwise this read fails closed.
    pub async fn fetch_for_recognition(
        &self,
        pool: &PgPool,
        pos_invoice_id: Uuid,
    ) -> Result<Option<RecognitionRow>, sqlx::Error> {
        let row = company_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                r#"SELECT i.company_id, i.customer_id, i.pos_profile_id, i.branch_id, i.posting_at, i.rounded_total, i.grand_total,
                          i.tax_total, i.paid_total, i.billing_invoice_id,
                          p.receivable_account_id, p.income_account_id, p.cash_account_id, p.tax_account_id, p.tax_rate,
                          p.warehouse_id, p.cogs_account_id, p.inventory_account_id,
                          p.currency, p.default_customer_id
                   FROM pos.pos_invoices i JOIN pos.pos_profiles p ON p.id = i.pos_profile_id
                   WHERE i.id=$1 AND i.status='draft'::pos_invoice_status AND (i.metadata->>'deleted_at') IS NULL"#,
            )
            .bind(pos_invoice_id),
        )
        .await?;
        Ok(row.map(|r| RecognitionRow {
            company_id: r.get("company_id"), customer_id: r.get("customer_id"), branch_id: r.get("branch_id"),
            posting_at: r.get("posting_at"), rounded_total: r.get("rounded_total"), grand_total: r.get("grand_total"),
            tax_total: r.get("tax_total"), paid_total: r.get("paid_total"),
            billing_invoice_id: r.get("billing_invoice_id"),
            receivable_account_id: r.get("receivable_account_id"), income_account_id: r.get("income_account_id"),
            cash_account_id: r.get("cash_account_id"), tax_account_id: r.get("tax_account_id"),
            tax_rate: r.get("tax_rate"), warehouse_id: r.get("warehouse_id"), cogs_account_id: r.get("cogs_account_id"),
            inventory_account_id: r.get("inventory_account_id"), currency: r.get("currency"),
            default_customer_id: r.get("default_customer_id"),
        }))
    }

    /// Persist the raised Sales Invoice onto the STILL-DRAFT ticket, before settle.
    ///
    /// This is billing's at-most-once gate (council 2026-07-05): writing the link the instant
    /// `raise_and_post` returns makes a retry after a settle failure (declined card / closed period)
    /// REUSE the invoice instead of raising a second one — otherwise the counter's ordinary
    /// decline-then-retry doubles the revenue journal. State-guarded on `draft`. Caller supplies the
    /// company scope.
    pub async fn link_billing_invoice(
        &self,
        pool: &PgPool,
        pos_invoice_id: Uuid,
        billing_invoice_id: Uuid,
    ) -> Result<(), sqlx::Error> {
        company_scope::execute_scoped(
            pool,
            sqlx::query("UPDATE pos.pos_invoices SET billing_invoice_id=$2 WHERE id=$1 AND status='draft'::pos_invoice_status")
                .bind(pos_invoice_id).bind(billing_invoice_id),
        )
        .await?;
        Ok(())
    }

    /// Flip a ticket draft→paid, persisting both downstream refs. Returns the rows affected: the caller
    /// gates the `PosInvoicePaid` event and the stock issue on this being 1, so each happens exactly
    /// once even if recognise is retried.
    ///
    /// Persisting `payment_entry_id` in the same flip is what lets a later return refund the tender from
    /// the ticket (no cross-schema lookup) and gives a crash-retry a durable skip-gate (ADR-001
    /// `settle`-idempotency). Caller supplies the company scope.
    pub async fn mark_paid(
        &self,
        pool: &PgPool,
        pos_invoice_id: Uuid,
        billing_invoice_id: Uuid,
        payment_entry_id: Uuid,
    ) -> Result<u64, sqlx::Error> {
        let res = company_scope::execute_scoped(
            pool,
            sqlx::query(
                "UPDATE pos.pos_invoices SET status='paid'::pos_invoice_status, billing_invoice_id=$2, payment_entry_id=$3 WHERE id=$1 AND status='draft'::pos_invoice_status",
            )
            .bind(pos_invoice_id).bind(billing_invoice_id).bind(payment_entry_id),
        )
        .await?;
        Ok(res.rows_affected())
    }

    /// Read the original ticket the returns path reverses and copies. Same ID-only scope contract as
    /// [`Self::fetch_tender_header`].
    pub async fn fetch_return_source(
        &self,
        pool: &PgPool,
        pos_invoice_id: Uuid,
    ) -> Result<Option<ReturnSourceRow>, sqlx::Error> {
        let row = company_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                r#"SELECT company_id, pos_profile_id, opening_entry_id, branch_id, customer_id, billing_invoice_id,
                          payment_entry_id, rounded_total, net_total, tax_total, grand_total, posting_at, status::text AS st
                   FROM pos.pos_invoices WHERE id=$1 AND (metadata->>'deleted_at') IS NULL"#,
            )
            .bind(pos_invoice_id),
        )
        .await?;
        Ok(row.map(|r| ReturnSourceRow {
            company_id: r.get("company_id"), pos_profile_id: r.get("pos_profile_id"),
            opening_entry_id: r.get("opening_entry_id"), branch_id: r.get("branch_id"),
            customer_id: r.get("customer_id"), billing_invoice_id: r.get("billing_invoice_id"),
            payment_entry_id: r.get("payment_entry_id"), rounded_total: r.get("rounded_total"),
            net_total: r.get("net_total"), tax_total: r.get("tax_total"), grand_total: r.get("grand_total"),
            posting_at: r.get("posting_at"), status: r.get("st"),
        }))
    }

    /// Flip the original ticket paid→returned. Returns the rows affected: the caller gates the return
    /// ticket and the `PosInvoiceReturned` event on this being 1, so a repeat return records at most
    /// once. Caller supplies the company scope.
    pub async fn mark_returned(
        &self,
        pool: &PgPool,
        pos_invoice_id: Uuid,
    ) -> Result<u64, sqlx::Error> {
        let res = company_scope::execute_scoped(
            pool,
            sqlx::query("UPDATE pos.pos_invoices SET status='returned'::pos_invoice_status WHERE id=$1 AND status='paid'::pos_invoice_status")
                .bind(pos_invoice_id),
        )
        .await?;
        Ok(res.rows_affected())
    }

    /// Insert the mirror return ticket, linked to the original via `return_against`. Caller supplies the
    /// company scope.
    pub async fn insert_return_ticket(
        &self,
        pool: &PgPool,
        r: &NewReturnInvoiceRow,
    ) -> Result<(), sqlx::Error> {
        company_scope::execute_scoped(
            pool,
            sqlx::query(
                r#"INSERT INTO pos.pos_invoices
                    (id, company_id, pos_profile_id, opening_entry_id, branch_id, customer_id, receipt_number,
                     posting_at, net_total, tax_total, grand_total, rounding_adjustment, rounded_total,
                     paid_total, change_due, billing_invoice_id, is_return, return_against, status)
                   VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,0,$12,$12,0,$13,true,$14,'returned'::pos_invoice_status)"#,
            )
            .bind(r.id).bind(r.company_id).bind(r.pos_profile_id).bind(r.opening_entry_id)
            .bind(r.branch_id).bind(r.customer_id).bind(&r.receipt_number)
            .bind(r.posting_at).bind(r.net_total).bind(r.tax_total).bind(r.grand_total).bind(r.rounded_total)
            .bind(r.billing_invoice_id).bind(r.return_against),
        )
        .await?;
        Ok(())
    }

    /// Find the return ticket already recorded against an original — the idempotent-replay path when the
    /// paid→returned flip found nothing to do. Caller supplies the company scope.
    pub async fn find_return_ticket(
        &self,
        pool: &PgPool,
        original_pos_invoice_id: Uuid,
    ) -> Result<Option<Uuid>, sqlx::Error> {
        company_scope::fetch_optional_scalar_scoped(
            pool,
            sqlx::query_scalar(
                "SELECT id FROM pos.pos_invoices WHERE return_against=$1 AND is_return=true AND (metadata->>'deleted_at') IS NULL LIMIT 1",
            )
            .bind(original_pos_invoice_id),
        )
        .await
    }

    /// Sum the cash handed back as change across a session's recognised tickets — it reduces the drawer.
    /// ID-only: the caller wraps it in `with_company_scope(Some(company))`.
    pub async fn sum_change_due_for_session(
        &self,
        pool: &PgPool,
        opening_entry_id: Uuid,
    ) -> Result<Decimal, sqlx::Error> {
        company_scope::fetch_one_scalar_scoped(
            pool,
            sqlx::query_scalar(
                "SELECT COALESCE(SUM(change_due),0) FROM pos.pos_invoices WHERE opening_entry_id=$1 AND status='paid'::pos_invoice_status AND (metadata->>'deleted_at') IS NULL",
            )
            .bind(opening_entry_id),
        )
        .await
    }

    /// A session's recognised turnover + paid-ticket count, for the X/Z report. ID-only: the caller
    /// wraps it in `with_company_scope(Some(company))`.
    pub async fn session_totals(
        &self,
        pool: &PgPool,
        opening_entry_id: Uuid,
    ) -> Result<(Decimal, i64), sqlx::Error> {
        company_scope::fetch_one_scoped(
            pool,
            sqlx::query_as(
                "SELECT COALESCE(SUM(rounded_total),0), COUNT(*) FROM pos.pos_invoices WHERE opening_entry_id=$1 AND status='paid'::pos_invoice_status AND (metadata->>'deleted_at') IS NULL",
            )
            .bind(opening_entry_id),
        )
        .await
    }

    /// Read a ticket header joined to its register for the printed receipt. `Ok(None)` = no such ticket
    /// in this tenant.
    ///
    /// The explicit `i.company_id = $2` filter is defense-in-depth ON TOP of the RLS fence; the company
    /// is on the parameter.
    pub async fn fetch_receipt_header(
        &self,
        pool: &PgPool,
        pos_invoice_id: Uuid,
        company_id: Uuid,
    ) -> Result<Option<ReceiptHeaderRow>, sqlx::Error> {
        let row = company_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                r#"SELECT i.receipt_number, i.posting_at, i.net_total, i.tax_total, i.rounding_adjustment,
                          i.rounded_total, i.paid_total, i.change_due, i.status::text AS status,
                          p.name AS register_name, p.currency, p.tax_rate
                   FROM pos.pos_invoices i JOIN pos.pos_profiles p ON p.id = i.pos_profile_id
                   WHERE i.id=$1 AND i.company_id=$2 AND (i.metadata->>'deleted_at') IS NULL"#,
            )
            .bind(pos_invoice_id).bind(company_id),
        )
        .await?;
        Ok(row.map(|r| ReceiptHeaderRow {
            receipt_number: r.get("receipt_number"), posting_at: r.get("posting_at"),
            net_total: r.get("net_total"), tax_total: r.get("tax_total"),
            rounding_adjustment: r.get("rounding_adjustment"), rounded_total: r.get("rounded_total"),
            paid_total: r.get("paid_total"), change_due: r.get("change_due"), status: r.get("status"),
            register_name: r.get("register_name"), currency: r.get("currency"), tax_rate: r.get("tax_rate"),
        }))
    }
}

backbone_core::impl_crud_repository!(PosInvoiceRepository, PosInvoice, soft_delete);
