//! Repository for PosProfile entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written register-configuration SQL (4-layer rule: services orchestrate, repos hold SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<PosProfile, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use rust_decimal::Decimal;
use sqlx::PgPool;
use uuid::Uuid;

use backbone_orm::company_scope;

use crate::domain::entity::PosProfile;

/// Table name for PosProfile entities
pub const TABLE_NAME: &str = "pos.pos_profiles";

/// Repository for PosProfile entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct PosProfileRepository(
    backbone_orm::GenericCrudRepository<PosProfile, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for PosProfileRepository {
    type Target = backbone_orm::GenericCrudRepository<PosProfile, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl PosProfileRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// Hand-written register-configuration SQL. Lives here (not in the write service) per the module's
/// 4-layer rule: services orchestrate and own the unit of work, repositories hold the SQL.
impl PosProfileRepository {
    /// Read a register's configured PPN rate. `Ok(None)` = no such register in this tenant.
    ///
    /// PPN is server-owned: this rate — not any client-supplied total — is what the ticket is taxed at.
    /// The explicit `company_id = $2` filter is defense-in-depth ON TOP of the RLS fence; the caller
    /// wraps this in `with_company_scope(Some(company))`.
    pub async fn fetch_tax_rate(
        &self,
        pool: &PgPool,
        pos_profile_id: Uuid,
        company_id: Uuid,
    ) -> Result<Option<Decimal>, sqlx::Error> {
        company_scope::fetch_optional_scalar_scoped(
            pool,
            sqlx::query_scalar(
                "SELECT tax_rate FROM pos.pos_profiles WHERE id=$1 AND company_id=$2 AND (metadata->>'deleted_at') IS NULL",
            )
            .bind(pos_profile_id).bind(company_id),
        )
        .await
    }
}

backbone_core::impl_crud_repository!(PosProfileRepository, PosProfile, soft_delete);
