//! Repository for PosProfile entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written register-configuration SQL (4-layer rule: services orchestrate, repos hold SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<PosProfile, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use rust_decimal::Decimal;
use sqlx::{PgPool, Row};
use uuid::Uuid;

use backbone_orm::company_scope;

use crate::domain::entity::PosProfile;

/// Table name for PosProfile entities
pub const TABLE_NAME: &str = "pos.pos_profiles";

/// Repository for PosProfile entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct PosProfileRepository(
    backbone_orm::GenericCrudRepository<PosProfile, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for PosProfileRepository {
    type Target = backbone_orm::GenericCrudRepository<PosProfile, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl PosProfileRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// A register's pricing-side configuration: the document-grade tax templates + the cash rounding
/// setup + the discount permission. Everything the ticket compute core and the order-discount gate
/// need from the profile.
pub struct TaxConfigRow {
    /// The register's tax template refs (`[template id, ...]`, logical refs to tax.TaxTemplate).
    pub tax_template_ids: Option<serde_json::Value>,
    /// Rounding strategy code: `none` or `half_up`.
    pub rounding_strategy: String,
    /// The rounding step (e.g. 100 for IDR); 0 = no rounding.
    pub rounding_unit: Decimal,
    /// Whether this register permits discounts. Gates the ORDER-LEVEL discount lane (a register
    /// configured discount-off refuses a ring that names a discount master row).
    pub allow_discount: bool,
}

/// Hand-written register-configuration SQL. Lives here (not in the write service) per the module's
/// 4-layer rule: services orchestrate and own the unit of work, repositories hold the SQL.
impl PosProfileRepository {
    /// Read a register's pricing-side configuration (tax templates + cash rounding).
    /// `Ok(None)` = no such register in this tenant.
    ///
    /// Tax is server-owned: these templates — not any client-supplied total — are what the ticket is
    /// taxed through (`PosTaxComputePort`). The explicit `company_id = $2` filter is defense-in-depth
    /// ON TOP of the RLS fence; the caller wraps this in `with_company_scope(Some(company))`.
    pub async fn fetch_tax_config(
        &self,
        pool: &PgPool,
        pos_profile_id: Uuid,
        company_id: Uuid,
    ) -> Result<Option<TaxConfigRow>, sqlx::Error> {
        let row = company_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                r#"SELECT tax_template_ids, cash_rounding_strategy::text AS strategy, cash_rounding_unit, allow_discount
                   FROM pos.pos_profiles WHERE id=$1 AND company_id=$2 AND (metadata->>'deleted_at') IS NULL"#,
            )
            .bind(pos_profile_id).bind(company_id),
        )
        .await?;
        Ok(row.map(|r| TaxConfigRow {
            tax_template_ids: r.get("tax_template_ids"),
            rounding_strategy: r.get("strategy"),
            rounding_unit: r.get("cash_rounding_unit"),
            allow_discount: r.get("allow_discount"),
        }))
    }
}

backbone_core::impl_crud_repository!(PosProfileRepository, PosProfile, soft_delete);
