//! Validator for PosFloorPlan entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<PosFloorPlan>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{RequiredString};
use crate::domain::entity::PosFloorPlan;

/// Validator type alias for PosFloorPlan entities.
pub type PosFloorPlanValidator = EntityValidator<PosFloorPlan>;

/// Build a validator for PosFloorPlan with all schema-defined field rules.
pub fn pos_floor_plan_validator() -> PosFloorPlanValidator {
    EntityValidator::new()
        .rule(RequiredString::new("name", |e: &PosFloorPlan| &e.name))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
