//! Validator for PosCashMovement entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<PosCashMovement>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative, OptionalNotBlank};
use crate::domain::entity::PosCashMovement;

/// Validator type alias for PosCashMovement entities.
pub type PosCashMovementValidator = EntityValidator<PosCashMovement>;

/// Build a validator for PosCashMovement with all schema-defined field rules.
pub fn pos_cash_movement_validator() -> PosCashMovementValidator {
    EntityValidator::new()
        .rule(OptionalNotBlank::new("reason", |e: &PosCashMovement| e.reason.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
