//! Validator for PosOpeningEntry entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<PosOpeningEntry>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use crate::domain::entity::PosOpeningEntry;

/// Validator type alias for PosOpeningEntry entities.
pub type PosOpeningEntryValidator = EntityValidator<PosOpeningEntry>;

/// Build a validator for PosOpeningEntry with all schema-defined field rules.
pub fn pos_opening_entry_validator() -> PosOpeningEntryValidator {
    EntityValidator::new()
    // <<< CUSTOM RULES
    // END CUSTOM RULES
        // No schema-derived rules — add custom rules above.
}

// <<< CUSTOM
// END CUSTOM
