//! Auth policies and guards
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod pos_closing_entry_auth;
pub mod pos_invoice_auth;
pub mod pos_invoice_item_auth;
pub mod pos_payment_auth;
pub mod pos_profile_auth;
pub mod pos_opening_entry_auth;

pub use pos_closing_entry_auth::{PosClosingEntryPolicy, PosClosingEntryGuard, PosClosingEntryServiceGuard};
pub use pos_invoice_auth::{PosInvoicePolicy, PosInvoiceGuard, PosInvoiceServiceGuard};
pub use pos_invoice_item_auth::{PosInvoiceItemPolicy, PosInvoiceItemGuard, PosInvoiceItemServiceGuard};
pub use pos_payment_auth::{PosPaymentPolicy, PosPaymentGuard, PosPaymentServiceGuard};
pub use pos_profile_auth::{PosProfilePolicy, PosProfileGuard, PosProfileServiceGuard};
pub use pos_opening_entry_auth::{PosOpeningEntryPolicy, PosOpeningEntryGuard, PosOpeningEntryServiceGuard};

// <<< CUSTOM
// END CUSTOM
