//! Auth configuration for PosClosingEntry handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<PosClosingEntry>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::PosClosingEntryService;
use crate::domain::entity::PosClosingEntry;

/// Permission string constants for PosClosingEntry operations.
pub mod permissions {
    pub const LIST:        &str = "pos_closing_entry:list";
    pub const READ:        &str = "pos_closing_entry:read";
    pub const CREATE:      &str = "pos_closing_entry:create";
    pub const UPDATE:      &str = "pos_closing_entry:update";
    pub const DELETE:      &str = "pos_closing_entry:delete";
    pub const RESTORE:     &str = "pos_closing_entry:restore";
    pub const TRASH:       &str = "pos_closing_entry:trash";
    pub const EMPTY_TRASH: &str = "pos_closing_entry:empty_trash";
    pub const BULK_CREATE: &str = "pos_closing_entry:bulk_create";
    pub const UPSERT:      &str = "pos_closing_entry:upsert";
}

/// Resource policy for PosClosingEntry — maps CRUD actions to permission strings.
pub struct PosClosingEntryPolicy;

#[async_trait]
impl ResourcePolicy<PosClosingEntry> for PosClosingEntryPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &PosClosingEntry,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for PosClosingEntry handlers.
///
/// Wraps `PosClosingEntryService` and checks `PosClosingEntryPolicy` before delegating.
pub type PosClosingEntryGuard = PermissionGuard<PosClosingEntry>;

/// Service-integrated permission guard for PosClosingEntry (for use in generated handlers).
pub type PosClosingEntryServiceGuard = ServicePermissionGuard<PosClosingEntry, PosClosingEntryService, PosClosingEntryPolicy>;

// <<< CUSTOM
// END CUSTOM
