//! Auth configuration for PosInvoiceItem handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<PosInvoiceItem>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::PosInvoiceItemService;
use crate::domain::entity::PosInvoiceItem;

/// Permission string constants for PosInvoiceItem operations.
pub mod permissions {
    pub const LIST:        &str = "pos_invoice_item:list";
    pub const READ:        &str = "pos_invoice_item:read";
    pub const CREATE:      &str = "pos_invoice_item:create";
    pub const UPDATE:      &str = "pos_invoice_item:update";
    pub const DELETE:      &str = "pos_invoice_item:delete";
    pub const RESTORE:     &str = "pos_invoice_item:restore";
    pub const TRASH:       &str = "pos_invoice_item:trash";
    pub const EMPTY_TRASH: &str = "pos_invoice_item:empty_trash";
    pub const BULK_CREATE: &str = "pos_invoice_item:bulk_create";
    pub const UPSERT:      &str = "pos_invoice_item:upsert";
}

/// Resource policy for PosInvoiceItem — maps CRUD actions to permission strings.
pub struct PosInvoiceItemPolicy;

#[async_trait]
impl ResourcePolicy<PosInvoiceItem> for PosInvoiceItemPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &PosInvoiceItem,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for PosInvoiceItem handlers.
///
/// Wraps `PosInvoiceItemService` and checks `PosInvoiceItemPolicy` before delegating.
pub type PosInvoiceItemGuard = PermissionGuard<PosInvoiceItem>;

/// Service-integrated permission guard for PosInvoiceItem (for use in generated handlers).
pub type PosInvoiceItemServiceGuard = ServicePermissionGuard<PosInvoiceItem, PosInvoiceItemService, PosInvoiceItemPolicy>;

// <<< CUSTOM
// END CUSTOM
