//! Auth configuration for PosOpeningEntry handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<PosOpeningEntry>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::PosOpeningEntryService;
use crate::domain::entity::PosOpeningEntry;

/// Permission string constants for PosOpeningEntry operations.
pub mod permissions {
    pub const LIST:        &str = "pos_opening_entry:list";
    pub const READ:        &str = "pos_opening_entry:read";
    pub const CREATE:      &str = "pos_opening_entry:create";
    pub const UPDATE:      &str = "pos_opening_entry:update";
    pub const DELETE:      &str = "pos_opening_entry:delete";
    pub const RESTORE:     &str = "pos_opening_entry:restore";
    pub const TRASH:       &str = "pos_opening_entry:trash";
    pub const EMPTY_TRASH: &str = "pos_opening_entry:empty_trash";
    pub const BULK_CREATE: &str = "pos_opening_entry:bulk_create";
    pub const UPSERT:      &str = "pos_opening_entry:upsert";
}

/// Resource policy for PosOpeningEntry — maps CRUD actions to permission strings.
pub struct PosOpeningEntryPolicy;

#[async_trait]
impl ResourcePolicy<PosOpeningEntry> for PosOpeningEntryPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &PosOpeningEntry,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for PosOpeningEntry handlers.
///
/// Wraps `PosOpeningEntryService` and checks `PosOpeningEntryPolicy` before delegating.
pub type PosOpeningEntryGuard = PermissionGuard<PosOpeningEntry>;

/// Service-integrated permission guard for PosOpeningEntry (for use in generated handlers).
pub type PosOpeningEntryServiceGuard = ServicePermissionGuard<PosOpeningEntry, PosOpeningEntryService, PosOpeningEntryPolicy>;

// <<< CUSTOM
// END CUSTOM
