//! PosInvoice API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the PosInvoice CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// POSINVOICE TEST DATA GENERATOR
// ============================================================================

/// Test data generator for PosInvoice
pub struct PosInvoiceTestData;

impl TestDataGenerator for PosInvoiceTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "pos_profile_id": Uuid::new_v4().to_string(),
            "opening_entry_id": Uuid::new_v4().to_string(),
            "branch_id": null,
            "customer_id": null,
            "receipt_number": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "posting_at": now,
            "net_total": 0,
            "tax_total": 0,
            "grand_total": 0,
            "rounding_adjustment": 0,
            "rounded_total": 0,
            "paid_total": 0,
            "change_due": 0,
            "billing_invoice_id": null,
            "payment_entry_id": null,
            "is_return": false,
            "return_against": null,
            "status": "draft",
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "company_id": Uuid::new_v4().to_string(),
            "pos_profile_id": Uuid::new_v4().to_string(),
            "opening_entry_id": Uuid::new_v4().to_string(),
            "branch_id": null,
            "customer_id": null,
            "receipt_number": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "posting_at": now,
            "net_total": 0,
            "tax_total": 0,
            "grand_total": 0,
            "rounding_adjustment": 0,
            "rounded_total": 0,
            "paid_total": 0,
            "change_due": 0,
            "billing_invoice_id": null,
            "payment_entry_id": null,
            "is_return": false,
            "return_against": null,
            "status": "draft",
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }

    async fn seed_dependencies(&self, api: &ApiTest) -> Vec<(String, String)> {
        let mut deps: Vec<(String, String)> = Vec::new();
        if let Some(id) = super::crud_test_base::create_and_get_id(api, "/api/v1/pos_opening_entries", &super::pos_opening_entry_api_test::PosOpeningEntryTestData).await {
            deps.push(("opening_entry_id".to_string(), id));
        }
        deps
    }
}

// ============================================================================
// POSINVOICE API TEST
// ============================================================================

/// PosInvoice API test suite
pub struct PosInvoiceApiTest {
    inner: GenericCrudTest<PosInvoiceTestData>,
}

impl PosInvoiceApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/pos_invoices", "PosInvoice");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, PosInvoiceTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for PosInvoiceApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_pos_invoice_crud() {
        let mut test = PosInvoiceApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add PosInvoice specific tests here
// <<< CUSTOM TESTS END >>>
