//! PosFloorPlan API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the PosFloorPlan CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// POSFLOORPLAN TEST DATA GENERATOR
// ============================================================================

/// Test data generator for PosFloorPlan
pub struct PosFloorPlanTestData;

impl TestDataGenerator for PosFloorPlanTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "branch_id": null,
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "position": null,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "company_id": Uuid::new_v4().to_string(),
            "branch_id": null,
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "position": null,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// POSFLOORPLAN API TEST
// ============================================================================

/// PosFloorPlan API test suite
pub struct PosFloorPlanApiTest {
    inner: GenericCrudTest<PosFloorPlanTestData>,
}

impl PosFloorPlanApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/pos_floor_plans", "PosFloorPlan");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, PosFloorPlanTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for PosFloorPlanApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_pos_floor_plan_crud() {
        let mut test = PosFloorPlanApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add PosFloorPlan specific tests here
// <<< CUSTOM TESTS END >>>
