//! PosInvoiceItem API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the PosInvoiceItem CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// POSINVOICEITEM TEST DATA GENERATOR
// ============================================================================

/// Test data generator for PosInvoiceItem
pub struct PosInvoiceItemTestData;

impl TestDataGenerator for PosInvoiceItemTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "pos_invoice_id": Uuid::new_v4().to_string(),
            "item_id": Uuid::new_v4().to_string(),
            "description": null,
            "client_uuid": null,
            "course": null,
            "quantity": 0,
            "unit_price": 0,
            "discount_amount": 0,
            "net_amount": 0,
            "revenue_account_id": null,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "company_id": Uuid::new_v4().to_string(),
            "pos_invoice_id": Uuid::new_v4().to_string(),
            "item_id": Uuid::new_v4().to_string(),
            "description": null,
            "client_uuid": null,
            "course": null,
            "quantity": 0,
            "unit_price": 0,
            "discount_amount": 0,
            "net_amount": 0,
            "revenue_account_id": null,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }

    async fn seed_dependencies(&self, api: &ApiTest) -> Vec<(String, String)> {
        let mut deps: Vec<(String, String)> = Vec::new();
        if let Some(id) = super::crud_test_base::create_and_get_id(api, "/api/v1/pos_invoices", &super::pos_invoice_api_test::PosInvoiceTestData).await {
            deps.push(("pos_invoice_id".to_string(), id));
        }
        deps
    }
}

// ============================================================================
// POSINVOICEITEM API TEST
// ============================================================================

/// PosInvoiceItem API test suite
pub struct PosInvoiceItemApiTest {
    inner: GenericCrudTest<PosInvoiceItemTestData>,
}

impl PosInvoiceItemApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/pos_invoice_items", "PosInvoiceItem");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, PosInvoiceItemTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for PosInvoiceItemApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_pos_invoice_item_crud() {
        let mut test = PosInvoiceItemApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add PosInvoiceItem specific tests here
// <<< CUSTOM TESTS END >>>
