//! PosCashMovement API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the PosCashMovement CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// POSCASHMOVEMENT TEST DATA GENERATOR
// ============================================================================

/// Test data generator for PosCashMovement
pub struct PosCashMovementTestData;

impl TestDataGenerator for PosCashMovementTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "pos_profile_id": Uuid::new_v4().to_string(),
            "opening_entry_id": Uuid::new_v4().to_string(),
            "cashier_party_id": Uuid::new_v4().to_string(),
            "movement_type": "pay_in",
            "amount": 0,
            "reason": null,
            "moved_at": now,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "company_id": Uuid::new_v4().to_string(),
            "pos_profile_id": Uuid::new_v4().to_string(),
            "opening_entry_id": Uuid::new_v4().to_string(),
            "cashier_party_id": Uuid::new_v4().to_string(),
            "movement_type": "pay_in",
            "amount": 0,
            "reason": null,
            "moved_at": now,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }

    async fn seed_dependencies(&self, api: &ApiTest) -> Vec<(String, String)> {
        let mut deps: Vec<(String, String)> = Vec::new();
        if let Some(id) = super::crud_test_base::create_and_get_id(api, "/api/v1/pos_opening_entries", &super::pos_opening_entry_api_test::PosOpeningEntryTestData).await {
            deps.push(("opening_entry_id".to_string(), id));
        }
        deps
    }
}

// ============================================================================
// POSCASHMOVEMENT API TEST
// ============================================================================

/// PosCashMovement API test suite
pub struct PosCashMovementApiTest {
    inner: GenericCrudTest<PosCashMovementTestData>,
}

impl PosCashMovementApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/pos_cash_movements", "PosCashMovement");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, PosCashMovementTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for PosCashMovementApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_pos_cash_movement_crud() {
        let mut test = PosCashMovementApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add PosCashMovement specific tests here
// <<< CUSTOM TESTS END >>>
