//! Data Transfer Objects
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.
//!
//! POS wire-shape DTOs live under `src/presentation/dto/`; this application-layer
//! module is currently empty (the generated entity DTOs are re-exported there).
