//! Public services for Pos module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These services provide the public API for other modules.
//! They only expose read operations - writes go through events.

use anyhow::Result;
use async_trait::async_trait;
use uuid::Uuid;

use super::types::*;

// ============================================================================
// QUERY SERVICE TRAIT
// ============================================================================

/// Public query service for Pos module
///
/// This trait defines read-only operations that other modules can use.
/// Implementations should NOT expose internal domain logic.
#[async_trait]
pub trait PosQueryService: Send + Sync {
    /// Get PosClosingEntry by ID
    async fn get_pos_closing_entry(&self, id: PosClosingEntryId) -> Result<Option<PosClosingEntryDto>>;

    /// Get PosClosingEntry summary by ID
    async fn get_pos_closing_entry_summary(&self, id: PosClosingEntryId) -> Result<Option<PosClosingEntrySummary>>;

    /// Check if PosClosingEntry exists
    async fn pos_closing_entry_exists(&self, id: PosClosingEntryId) -> Result<bool>;

    /// Get PosInvoice by ID
    async fn get_pos_invoice(&self, id: PosInvoiceId) -> Result<Option<PosInvoiceDto>>;

    /// Get PosInvoice summary by ID
    async fn get_pos_invoice_summary(&self, id: PosInvoiceId) -> Result<Option<PosInvoiceSummary>>;

    /// Check if PosInvoice exists
    async fn pos_invoice_exists(&self, id: PosInvoiceId) -> Result<bool>;

    /// Get PosInvoiceItem by ID
    async fn get_pos_invoice_item(&self, id: PosInvoiceItemId) -> Result<Option<PosInvoiceItemDto>>;

    /// Get PosInvoiceItem summary by ID
    async fn get_pos_invoice_item_summary(&self, id: PosInvoiceItemId) -> Result<Option<PosInvoiceItemSummary>>;

    /// Check if PosInvoiceItem exists
    async fn pos_invoice_item_exists(&self, id: PosInvoiceItemId) -> Result<bool>;

    /// Get PosPayment by ID
    async fn get_pos_payment(&self, id: PosPaymentId) -> Result<Option<PosPaymentDto>>;

    /// Get PosPayment summary by ID
    async fn get_pos_payment_summary(&self, id: PosPaymentId) -> Result<Option<PosPaymentSummary>>;

    /// Check if PosPayment exists
    async fn pos_payment_exists(&self, id: PosPaymentId) -> Result<bool>;

    /// Get PosProfile by ID
    async fn get_pos_profile(&self, id: PosProfileId) -> Result<Option<PosProfileDto>>;

    /// Get PosProfile summary by ID
    async fn get_pos_profile_summary(&self, id: PosProfileId) -> Result<Option<PosProfileSummary>>;

    /// Check if PosProfile exists
    async fn pos_profile_exists(&self, id: PosProfileId) -> Result<bool>;

    /// Get PosOpeningEntry by ID
    async fn get_pos_opening_entry(&self, id: PosOpeningEntryId) -> Result<Option<PosOpeningEntryDto>>;

    /// Get PosOpeningEntry summary by ID
    async fn get_pos_opening_entry_summary(&self, id: PosOpeningEntryId) -> Result<Option<PosOpeningEntrySummary>>;

    /// Check if PosOpeningEntry exists
    async fn pos_opening_entry_exists(&self, id: PosOpeningEntryId) -> Result<bool>;

    /// Get PosCashMovement by ID
    async fn get_pos_cash_movement(&self, id: PosCashMovementId) -> Result<Option<PosCashMovementDto>>;

    /// Get PosCashMovement summary by ID
    async fn get_pos_cash_movement_summary(&self, id: PosCashMovementId) -> Result<Option<PosCashMovementSummary>>;

    /// Check if PosCashMovement exists
    async fn pos_cash_movement_exists(&self, id: PosCashMovementId) -> Result<bool>;

}

// ============================================================================
// CUSTOM SERVICES
// ============================================================================

// <<< CUSTOM SERVICES START >>>
// Add custom public services here
// <<< CUSTOM SERVICES END >>>
