//! Public types for Pos module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These DTOs are the ONLY types other modules should use.
//! They are decoupled from internal domain entities.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};
use rust_decimal::Decimal;
use crate::domain::entity::*;

// ============================================================================
// POSCLOSINGENTRY TYPES
// ============================================================================

/// Type-safe ID for PosClosingEntry
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct PosClosingEntryId(pub Uuid);

impl PosClosingEntryId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for PosClosingEntryId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<PosClosingEntryId> for Uuid {
    fn from(id: PosClosingEntryId) -> Self {
        id.0
    }
}

/// Data transfer object for PosClosingEntry
///
/// This is the public representation of PosClosingEntry for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PosClosingEntryDto {
    pub id: PosClosingEntryId,
    pub company_id: Uuid,
    pub pos_profile_id: Uuid,
    pub opening_entry_id: Uuid,
    pub closed_at: DateTime<Utc>,
    pub cashier_party_id: Uuid,
    pub totals_by_method: Option<serde_json::Value>,
    pub grand_total: Decimal,
    pub invoice_count: i32,
    pub difference_total: Decimal,
    pub status: PosClosingStatus,
    pub metadata: serde_json::Value,
}

/// Summary view of PosClosingEntry for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PosClosingEntrySummary {
    pub id: PosClosingEntryId,
    pub status: PosClosingStatus,
}

/// Reference to PosClosingEntry for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PosClosingEntryRef {
    pub id: PosClosingEntryId,
}

// ============================================================================
// POSINVOICE TYPES
// ============================================================================

/// Type-safe ID for PosInvoice
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct PosInvoiceId(pub Uuid);

impl PosInvoiceId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for PosInvoiceId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<PosInvoiceId> for Uuid {
    fn from(id: PosInvoiceId) -> Self {
        id.0
    }
}

/// Data transfer object for PosInvoice
///
/// This is the public representation of PosInvoice for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PosInvoiceDto {
    pub id: PosInvoiceId,
    pub company_id: Uuid,
    pub pos_profile_id: Uuid,
    pub opening_entry_id: Uuid,
    pub branch_id: Option<Uuid>,
    pub customer_id: Option<Uuid>,
    pub receipt_number: String,
    pub posting_at: DateTime<Utc>,
    pub net_total: Decimal,
    pub tax_total: Decimal,
    pub grand_total: Decimal,
    pub rounding_adjustment: Decimal,
    pub rounded_total: Decimal,
    pub paid_total: Decimal,
    pub change_due: Decimal,
    pub billing_invoice_id: Option<Uuid>,
    pub payment_entry_id: Option<Uuid>,
    pub is_return: bool,
    pub return_against: Option<Uuid>,
    pub status: PosInvoiceStatus,
    pub metadata: serde_json::Value,
}

/// Summary view of PosInvoice for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PosInvoiceSummary {
    pub id: PosInvoiceId,
    pub status: PosInvoiceStatus,
}

/// Reference to PosInvoice for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PosInvoiceRef {
    pub id: PosInvoiceId,
}

// ============================================================================
// POSINVOICEITEM TYPES
// ============================================================================

/// Type-safe ID for PosInvoiceItem
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct PosInvoiceItemId(pub Uuid);

impl PosInvoiceItemId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for PosInvoiceItemId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<PosInvoiceItemId> for Uuid {
    fn from(id: PosInvoiceItemId) -> Self {
        id.0
    }
}

/// Data transfer object for PosInvoiceItem
///
/// This is the public representation of PosInvoiceItem for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PosInvoiceItemDto {
    pub id: PosInvoiceItemId,
    pub pos_invoice_id: Uuid,
    pub item_id: Uuid,
    pub description: Option<String>,
    pub quantity: Decimal,
    pub unit_price: Decimal,
    pub discount_amount: Decimal,
    pub net_amount: Decimal,
    pub revenue_account_id: Option<Uuid>,
    pub metadata: serde_json::Value,
}

/// Summary view of PosInvoiceItem for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PosInvoiceItemSummary {
    pub id: PosInvoiceItemId,
}

/// Reference to PosInvoiceItem for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PosInvoiceItemRef {
    pub id: PosInvoiceItemId,
}

// ============================================================================
// POSPAYMENT TYPES
// ============================================================================

/// Type-safe ID for PosPayment
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct PosPaymentId(pub Uuid);

impl PosPaymentId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for PosPaymentId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<PosPaymentId> for Uuid {
    fn from(id: PosPaymentId) -> Self {
        id.0
    }
}

/// Data transfer object for PosPayment
///
/// This is the public representation of PosPayment for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PosPaymentDto {
    pub id: PosPaymentId,
    pub pos_invoice_id: Uuid,
    pub payment_method: PosPaymentMethod,
    pub amount: Decimal,
    pub reference_no: Option<String>,
    pub payment_entry_id: Option<Uuid>,
    pub metadata: serde_json::Value,
}

/// Summary view of PosPayment for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PosPaymentSummary {
    pub id: PosPaymentId,
}

/// Reference to PosPayment for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PosPaymentRef {
    pub id: PosPaymentId,
}

// ============================================================================
// POSPROFILE TYPES
// ============================================================================

/// Type-safe ID for PosProfile
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct PosProfileId(pub Uuid);

impl PosProfileId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for PosProfileId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<PosProfileId> for Uuid {
    fn from(id: PosProfileId) -> Self {
        id.0
    }
}

/// Data transfer object for PosProfile
///
/// This is the public representation of PosProfile for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PosProfileDto {
    pub id: PosProfileId,
    pub company_id: Uuid,
    pub branch_id: Option<Uuid>,
    pub name: String,
    pub default_customer_id: Option<Uuid>,
    pub currency: String,
    pub income_account_id: Option<Uuid>,
    pub receivable_account_id: Option<Uuid>,
    pub cash_account_id: Option<Uuid>,
    pub write_off_account_id: Option<Uuid>,
    pub allow_discount: bool,
    pub is_active: bool,
    pub metadata: serde_json::Value,
}

/// Summary view of PosProfile for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PosProfileSummary {
    pub id: PosProfileId,
    pub name: String,
}

/// Reference to PosProfile for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PosProfileRef {
    pub id: PosProfileId,
}

// ============================================================================
// POSOPENINGENTRY TYPES
// ============================================================================

/// Type-safe ID for PosOpeningEntry
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct PosOpeningEntryId(pub Uuid);

impl PosOpeningEntryId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for PosOpeningEntryId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<PosOpeningEntryId> for Uuid {
    fn from(id: PosOpeningEntryId) -> Self {
        id.0
    }
}

/// Data transfer object for PosOpeningEntry
///
/// This is the public representation of PosOpeningEntry for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PosOpeningEntryDto {
    pub id: PosOpeningEntryId,
    pub company_id: Uuid,
    pub pos_profile_id: Uuid,
    pub branch_id: Option<Uuid>,
    pub cashier_party_id: Uuid,
    pub opened_at: DateTime<Utc>,
    pub opening_balances: Option<serde_json::Value>,
    pub status: PosSessionStatus,
    pub metadata: serde_json::Value,
}

/// Summary view of PosOpeningEntry for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PosOpeningEntrySummary {
    pub id: PosOpeningEntryId,
    pub status: PosSessionStatus,
}

/// Reference to PosOpeningEntry for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PosOpeningEntryRef {
    pub id: PosOpeningEntryId,
}

// ============================================================================
// POSCASHMOVEMENT TYPES
// ============================================================================

/// Type-safe ID for PosCashMovement
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct PosCashMovementId(pub Uuid);

impl PosCashMovementId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for PosCashMovementId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<PosCashMovementId> for Uuid {
    fn from(id: PosCashMovementId) -> Self {
        id.0
    }
}

/// Data transfer object for PosCashMovement
///
/// This is the public representation of PosCashMovement for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PosCashMovementDto {
    pub id: PosCashMovementId,
    pub company_id: Uuid,
    pub pos_profile_id: Uuid,
    pub opening_entry_id: Uuid,
    pub cashier_party_id: Uuid,
    pub movement_type: PosCashMovementType,
    pub amount: Decimal,
    pub reason: Option<String>,
    pub moved_at: DateTime<Utc>,
    pub metadata: serde_json::Value,
}

/// Summary view of PosCashMovement for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PosCashMovementSummary {
    pub id: PosCashMovementId,
}

/// Reference to PosCashMovement for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PosCashMovementRef {
    pub id: PosCashMovementId,
}

// ============================================================================
// CUSTOM TYPES
// ============================================================================

// <<< CUSTOM TYPES START >>>
// Add custom public types here
// <<< CUSTOM TYPES END >>>
