//! Pos Module
//!
//! Generated by metaphor-schema. Enhanced with runtime implementations.
//!
//! This module provides:
//! - Domain entities and repositories
//! - Application services
//! - HTTP and gRPC handlers
//! - Route configuration
//! - State machine enforcement
//! - Validation rules runtime
//! - RBAC middleware
//! - Trigger execution system
//! - Computed fields
//! - Workflow orchestrator

#![recursion_limit = "1024"]
#![allow(unused_imports)]

// Generated modules
pub mod domain;
pub mod infrastructure;
pub mod application;
pub mod presentation;
pub mod seeders;

// <<< CUSTOM
/// Stable integration surface for composing services (the deliberate public API consumers depend on).
pub mod integration;
// END CUSTOM
// Re-exports for convenience - Domain entities
pub use domain::entity::*;

// Re-exports - Infrastructure
pub use infrastructure::persistence::*;

// Re-exports - Application services
pub use application::service::PosClosingEntryService;
pub use application::service::PosInvoiceService;
pub use application::service::PosInvoiceItemService;
pub use application::service::PosPaymentService;
pub use application::service::PosProfileService;
pub use application::service::PosOpeningEntryService;
pub use application::service::PosCashMovementService;

use std::sync::Arc;
use axum::Router;
use sqlx::PgPool;

/// Pos module configuration
///
/// Use the builder pattern to configure and register this module:
///
/// ```text
/// let pos = PosModule::builder()
///     .with_database(pool.clone())
///     .build()?;
///
/// // Unguarded full CRUD (trusted/admin); compose a guarded router for production.
/// let router = pos.all_crud_routes();
/// ```
pub struct PosModule {
    pub pos_closing_entry_service: Arc<PosClosingEntryService>,
    pub pos_invoice_service: Arc<PosInvoiceService>,
    pub pos_invoice_item_service: Arc<PosInvoiceItemService>,
    pub pos_payment_service: Arc<PosPaymentService>,
    pub pos_profile_service: Arc<PosProfileService>,
    pub pos_opening_entry_service: Arc<PosOpeningEntryService>,
    pub pos_cash_movement_service: Arc<PosCashMovementService>,
}

impl PosModule {
    /// Create a new module builder
    pub fn builder() -> PosModuleBuilder {
        PosModuleBuilder::new()
    }

    /// Mount ALL generated CRUD endpoints (12 per entity) with NO domain
    /// validation — the fully **unguarded** surface. A well-formed request can
    /// create invalid rows or soft-delete a referenced master out from under its
    /// dependents. Prefer a guarded composition (read + validated writes) for any
    /// real deployment; use this only in trusted/admin/seeding contexts.
    pub fn all_crud_routes(&self) -> Router {
        use presentation::http::{
            create_pos_closing_entry_routes,
            create_pos_invoice_routes,
            create_pos_invoice_item_routes,
            create_pos_payment_routes,
            create_pos_profile_routes,
            create_pos_opening_entry_routes,
            create_pos_cash_movement_routes,
        };

        Router::new()
            .merge(create_pos_closing_entry_routes(self.pos_closing_entry_service.clone()))
            .merge(create_pos_invoice_routes(self.pos_invoice_service.clone()))
            .merge(create_pos_invoice_item_routes(self.pos_invoice_item_service.clone()))
            .merge(create_pos_payment_routes(self.pos_payment_service.clone()))
            .merge(create_pos_profile_routes(self.pos_profile_service.clone()))
            .merge(create_pos_opening_entry_routes(self.pos_opening_entry_service.clone()))
            .merge(create_pos_cash_movement_routes(self.pos_cash_movement_service.clone()))
    }

    /// Deprecated alias for [`Self::all_crud_routes`]. `routes()` reads like
    /// "the routes" but mounts UNVALIDATED generic CRUD on every entity — a naive
    /// mount exposes unguarded writes. Compose a guarded router (read + validated
    /// writes) for production, or call `all_crud_routes()` to opt into the full
    /// unguarded surface explicitly.
    #[deprecated(note = "mounts unvalidated generic CRUD on every entity; compose a guarded router for production, or call all_crud_routes() for the intentional full/unguarded surface")]
    pub fn routes(&self) -> Router {
        self.all_crud_routes()
    }
}

/// Builder for PosModule
pub struct PosModuleBuilder {
    db_pool: Option<PgPool>,
}

impl PosModuleBuilder {
    /// Create a new builder
    pub fn new() -> Self {
        Self {
            db_pool: None,
        }
    }

    /// Set the database connection pool
    pub fn with_database(mut self, pool: PgPool) -> Self {
        self.db_pool = Some(pool);
        self
    }

    // <<< CUSTOM - custom builder methods
    // END CUSTOM

    /// Build the module with configured dependencies
    pub fn build(self) -> anyhow::Result<PosModule> {
        let db_pool = self.db_pool
            .ok_or_else(|| anyhow::anyhow!("Database pool not configured"))?;

        // PosClosingEntry service
        let pos_closing_entry_repository = Arc::new(PosClosingEntryRepository::new(db_pool.clone()));
        let pos_closing_entry_service = Arc::new(PosClosingEntryService::with_repository(pos_closing_entry_repository.clone()));

        // PosInvoice service
        let pos_invoice_repository = Arc::new(PosInvoiceRepository::new(db_pool.clone()));
        let pos_invoice_service = Arc::new(PosInvoiceService::with_repository(pos_invoice_repository.clone()));

        // PosInvoiceItem service
        let pos_invoice_item_repository = Arc::new(PosInvoiceItemRepository::new(db_pool.clone()));
        let pos_invoice_item_service = Arc::new(PosInvoiceItemService::with_repository(pos_invoice_item_repository.clone()));

        // PosPayment service
        let pos_payment_repository = Arc::new(PosPaymentRepository::new(db_pool.clone()));
        let pos_payment_service = Arc::new(PosPaymentService::with_repository(pos_payment_repository.clone()));

        // PosProfile service
        let pos_profile_repository = Arc::new(PosProfileRepository::new(db_pool.clone()));
        let pos_profile_service = Arc::new(PosProfileService::with_repository(pos_profile_repository.clone()));

        // PosOpeningEntry service
        let pos_opening_entry_repository = Arc::new(PosOpeningEntryRepository::new(db_pool.clone()));
        let pos_opening_entry_service = Arc::new(PosOpeningEntryService::with_repository(pos_opening_entry_repository.clone()));

        // PosCashMovement service
        let pos_cash_movement_repository = Arc::new(PosCashMovementRepository::new(db_pool.clone()));
        let pos_cash_movement_service = Arc::new(PosCashMovementService::with_repository(pos_cash_movement_repository.clone()));

        // <<< CUSTOM
        // END CUSTOM

        Ok(PosModule {
            pos_closing_entry_service,
            pos_invoice_service,
            pos_invoice_item_service,
            pos_payment_service,
            pos_profile_service,
            pos_opening_entry_service,
            pos_cash_movement_service,
            // <<< CUSTOM
            // END CUSTOM
        })
    }
}

impl Default for PosModuleBuilder {
    fn default() -> Self {
        Self::new()
    }
}