//! Application use cases
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity contributes 5 type aliases (create, update, get, delete, list).

pub mod base;
pub use base::{UseCaseError, UseCaseResult, UseCaseHooks};

pub mod pos_closing_entry_usecases;
pub mod pos_invoice_usecases;
pub mod pos_invoice_item_usecases;
pub mod pos_payment_usecases;
pub mod pos_profile_usecases;
pub mod pos_opening_entry_usecases;
pub mod pos_cash_movement_usecases;

pub use pos_closing_entry_usecases::{
    CreatePosClosingEntryUseCase, UpdatePosClosingEntryUseCase, GetPosClosingEntryUseCase,
    DeletePosClosingEntryUseCase, ListPosClosingEntryUseCase,
};
pub use pos_invoice_usecases::{
    CreatePosInvoiceUseCase, UpdatePosInvoiceUseCase, GetPosInvoiceUseCase,
    DeletePosInvoiceUseCase, ListPosInvoiceUseCase,
};
pub use pos_invoice_item_usecases::{
    CreatePosInvoiceItemUseCase, UpdatePosInvoiceItemUseCase, GetPosInvoiceItemUseCase,
    DeletePosInvoiceItemUseCase, ListPosInvoiceItemUseCase,
};
pub use pos_payment_usecases::{
    CreatePosPaymentUseCase, UpdatePosPaymentUseCase, GetPosPaymentUseCase,
    DeletePosPaymentUseCase, ListPosPaymentUseCase,
};
pub use pos_profile_usecases::{
    CreatePosProfileUseCase, UpdatePosProfileUseCase, GetPosProfileUseCase,
    DeletePosProfileUseCase, ListPosProfileUseCase,
};
pub use pos_opening_entry_usecases::{
    CreatePosOpeningEntryUseCase, UpdatePosOpeningEntryUseCase, GetPosOpeningEntryUseCase,
    DeletePosOpeningEntryUseCase, ListPosOpeningEntryUseCase,
};
pub use pos_cash_movement_usecases::{
    CreatePosCashMovementUseCase, UpdatePosCashMovementUseCase, GetPosCashMovementUseCase,
    DeletePosCashMovementUseCase, ListPosCashMovementUseCase,
};

// <<< CUSTOM
// END CUSTOM
