//! Use case type aliases for PosProfile aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreatePosProfileDto, UpdatePosProfileDto};
use crate::application::service::PosProfileService;
use crate::domain::entity::PosProfile;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreatePosProfileUseCase = CreateUseCase<PosProfile, CreatePosProfileDto, PosProfileService>;
pub type UpdatePosProfileUseCase = UpdateUseCase<PosProfile, UpdatePosProfileDto, PosProfileService>;
pub type GetPosProfileUseCase    = GetUseCase<PosProfile, PosProfileService>;
pub type DeletePosProfileUseCase = DeleteUseCase<PosProfile, PosProfileService>;
pub type ListPosProfileUseCase   = ListUseCase<PosProfile, PosProfileService>;

// <<< CUSTOM
// END CUSTOM
