//! Use case type aliases for PosPayment aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreatePosPaymentDto, UpdatePosPaymentDto};
use crate::application::service::PosPaymentService;
use crate::domain::entity::PosPayment;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreatePosPaymentUseCase = CreateUseCase<PosPayment, CreatePosPaymentDto, PosPaymentService>;
pub type UpdatePosPaymentUseCase = UpdateUseCase<PosPayment, UpdatePosPaymentDto, PosPaymentService>;
pub type GetPosPaymentUseCase    = GetUseCase<PosPayment, PosPaymentService>;
pub type DeletePosPaymentUseCase = DeleteUseCase<PosPayment, PosPaymentService>;
pub type ListPosPaymentUseCase   = ListUseCase<PosPayment, PosPaymentService>;

// <<< CUSTOM
// END CUSTOM
