//! Use case type aliases for PosCashMovement aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreatePosCashMovementDto, UpdatePosCashMovementDto};
use crate::application::service::PosCashMovementService;
use crate::domain::entity::PosCashMovement;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreatePosCashMovementUseCase = CreateUseCase<PosCashMovement, CreatePosCashMovementDto, PosCashMovementService>;
pub type UpdatePosCashMovementUseCase = UpdateUseCase<PosCashMovement, UpdatePosCashMovementDto, PosCashMovementService>;
pub type GetPosCashMovementUseCase    = GetUseCase<PosCashMovement, PosCashMovementService>;
pub type DeletePosCashMovementUseCase = DeleteUseCase<PosCashMovement, PosCashMovementService>;
pub type ListPosCashMovementUseCase   = ListUseCase<PosCashMovement, PosCashMovementService>;

// <<< CUSTOM
// END CUSTOM
